// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RecordingRow indexes one saved recording with its descriptive metadata.
 */
export class RecordingRow {
    "name": string;
    "track": string;
    "car": string;
    "source": string;

    /**
     * unix seconds
     */
    "recorded_at": number;
    "size_bytes": number;

    /** Creates a new RecordingRow instance. */
    constructor($$source: Partial<RecordingRow> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("track" in $$source)) {
            this["track"] = "";
        }
        if (!("car" in $$source)) {
            this["car"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("recorded_at" in $$source)) {
            this["recorded_at"] = 0;
        }
        if (!("size_bytes" in $$source)) {
            this["size_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingRow instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordingRow($$parsedSource as Partial<RecordingRow>);
    }
}

/**
 * SessionRow is one stint/session in the history.
 */
export class SessionRow {
    "id": number;
    "track": string;
    "car": string;

    /**
     * unix seconds
     */
    "started_at": number;

    /**
     * unix seconds
     */
    "ended_at": number;
    "laps": number;

    /**
     * seconds
     */
    "best_lap": number;

    /** Creates a new SessionRow instance. */
    constructor($$source: Partial<SessionRow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("track" in $$source)) {
            this["track"] = "";
        }
        if (!("car" in $$source)) {
            this["car"] = "";
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = 0;
        }
        if (!("ended_at" in $$source)) {
            this["ended_at"] = 0;
        }
        if (!("laps" in $$source)) {
            this["laps"] = 0;
        }
        if (!("best_lap" in $$source)) {
            this["best_lap"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRow instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRow($$parsedSource as Partial<SessionRow>);
    }
}
