// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export type Color = number[];

export class Config {
    "listen_addr": string;
    "listen_port": number;
    "print_hz": number;
    "moza": Moza;
    "recording": Recording;
    "terminal_print": Terminal;
    "overlay": Overlay;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("listen_addr" in $$source)) {
            this["listen_addr"] = "";
        }
        if (!("listen_port" in $$source)) {
            this["listen_port"] = 0;
        }
        if (!("print_hz" in $$source)) {
            this["print_hz"] = 0;
        }
        if (!("moza" in $$source)) {
            this["moza"] = (new Moza());
        }
        if (!("recording" in $$source)) {
            this["recording"] = (new Recording());
        }
        if (!("terminal_print" in $$source)) {
            this["terminal_print"] = (new Terminal());
        }
        if (!("overlay" in $$source)) {
            this["overlay"] = (new Overlay());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("moza" in $$parsedSource) {
            $$parsedSource["moza"] = $$createField3_0($$parsedSource["moza"]);
        }
        if ("recording" in $$parsedSource) {
            $$parsedSource["recording"] = $$createField4_0($$parsedSource["recording"]);
        }
        if ("terminal_print" in $$parsedSource) {
            $$parsedSource["terminal_print"] = $$createField5_0($$parsedSource["terminal_print"]);
        }
        if ("overlay" in $$parsedSource) {
            $$parsedSource["overlay"] = $$createField6_0($$parsedSource["overlay"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class Moza {
    "enabled": boolean;
    "port": string;
    "update_hz": number;
    "rpm_brightness": number;
    "rpm_colors": Color[];
    "button_colors": Color[];
    "button_mask": number;

    /**
     * RPMLEDs manually sets the number of rev-light segments on the wheel rim.
     * The rim is not identifiable over USB (only the base is), so when the base's
     * default profile does not match the attached rim, set this to override it.
     * 0 means "auto" — use the detected base's profile (or the default).
     */
    "rpm_leds"?: number;

    /** Creates a new Moza instance. */
    constructor($$source: Partial<Moza> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("update_hz" in $$source)) {
            this["update_hz"] = 0;
        }
        if (!("rpm_brightness" in $$source)) {
            this["rpm_brightness"] = 0;
        }
        if (!("rpm_colors" in $$source)) {
            this["rpm_colors"] = Array.from({ length: 10 }, () => Array.from({ length: 3 }, () => 0));
        }
        if (!("button_colors" in $$source)) {
            this["button_colors"] = Array.from({ length: 10 }, () => Array.from({ length: 3 }, () => 0));
        }
        if (!("button_mask" in $$source)) {
            this["button_mask"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Moza instance from a string or object.
     */
    static createFrom($$source: any = {}): Moza {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Moza($$parsedSource as Partial<Moza>);
    }
}

export class Overlay {
    "enabled": boolean;
    "output"?: string;
    "game_window_match"?: string;
    "width"?: number | null;
    "height"?: number | null;
    "anchor": string;
    "margin_top"?: number | null;
    "margin_right"?: number | null;
    "margin_bottom"?: number | null;
    "margin_left"?: number | null;
    "update_hz": number;
    "opacity": number;
    "show_steering": boolean;
    "steering_image_path"?: string;
    "steering_size"?: number | null;

    /**
     * SteeringX/SteeringY position the steering wheel within the overlay box
     * (top-left origin, logical pixels). When nil they fall back to the legacy
     * auto-placement (top-right corner) — see SteeringXValue/SteeringYValue.
     */
    "steering_x"?: number | null;
    "steering_y"?: number | null;

    /**
     * SteeringRangeDeg is the lock-to-lock wheel rotation (degrees) used to map
     * the steering input to the displayed wheel angle. It is the fallback for
     * games that do not report a range (Forza); LMU reports a per-car range that
     * overrides it. 0 means "use the default".
     */
    "steering_range_deg"?: number;

    /** Creates a new Overlay instance. */
    constructor($$source: Partial<Overlay> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("anchor" in $$source)) {
            this["anchor"] = "";
        }
        if (!("update_hz" in $$source)) {
            this["update_hz"] = 0;
        }
        if (!("opacity" in $$source)) {
            this["opacity"] = 0;
        }
        if (!("show_steering" in $$source)) {
            this["show_steering"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overlay instance from a string or object.
     */
    static createFrom($$source: any = {}): Overlay {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Overlay($$parsedSource as Partial<Overlay>);
    }
}

export class Recording {
    "dir": string;

    /** Creates a new Recording instance. */
    constructor($$source: Partial<Recording> = {}) {
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recording instance from a string or object.
     */
    static createFrom($$source: any = {}): Recording {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recording($$parsedSource as Partial<Recording>);
    }
}

export class Terminal {
    "enabled": boolean;

    /** Creates a new Terminal instance. */
    constructor($$source: Partial<Terminal> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Terminal instance from a string or object.
     */
    static createFrom($$source: any = {}): Terminal {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Terminal($$parsedSource as Partial<Terminal>);
    }
}

// Private type creation functions
const $$createType0 = Moza.createFrom;
const $$createType1 = Recording.createFrom;
const $$createType2 = Terminal.createFrom;
const $$createType3 = Overlay.createFrom;
