// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export type Color = number[];

export class Config {
    "listen_addr": string;
    "listen_port": number;
    "print_hz": number;
    "moza": Moza;
    "recording": Recording;
    "terminal_print": Terminal;
    "overlay": Overlay;
    "lmu": LMU;
    "voice": Voice;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("listen_addr" in $$source)) {
            this["listen_addr"] = "";
        }
        if (!("listen_port" in $$source)) {
            this["listen_port"] = 0;
        }
        if (!("print_hz" in $$source)) {
            this["print_hz"] = 0;
        }
        if (!("moza" in $$source)) {
            this["moza"] = (new Moza());
        }
        if (!("recording" in $$source)) {
            this["recording"] = (new Recording());
        }
        if (!("terminal_print" in $$source)) {
            this["terminal_print"] = (new Terminal());
        }
        if (!("overlay" in $$source)) {
            this["overlay"] = (new Overlay());
        }
        if (!("lmu" in $$source)) {
            this["lmu"] = (new LMU());
        }
        if (!("voice" in $$source)) {
            this["voice"] = (new Voice());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("moza" in $$parsedSource) {
            $$parsedSource["moza"] = $$createField3_0($$parsedSource["moza"]);
        }
        if ("recording" in $$parsedSource) {
            $$parsedSource["recording"] = $$createField4_0($$parsedSource["recording"]);
        }
        if ("terminal_print" in $$parsedSource) {
            $$parsedSource["terminal_print"] = $$createField5_0($$parsedSource["terminal_print"]);
        }
        if ("overlay" in $$parsedSource) {
            $$parsedSource["overlay"] = $$createField6_0($$parsedSource["overlay"]);
        }
        if ("lmu" in $$parsedSource) {
            $$parsedSource["lmu"] = $$createField7_0($$parsedSource["lmu"]);
        }
        if ("voice" in $$parsedSource) {
            $$parsedSource["voice"] = $$createField8_0($$parsedSource["voice"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * CurvePoint is one control point of the MOZA rev-light response curve. X is the
 * input RPM ratio (current/max) and Y the output bar fill, both in [0,1].
 */
export class CurvePoint {
    "x": number;
    "y": number;

    /** Creates a new CurvePoint instance. */
    constructor($$source: Partial<CurvePoint> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CurvePoint instance from a string or object.
     */
    static createFrom($$source: any = {}): CurvePoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CurvePoint($$parsedSource as Partial<CurvePoint>);
    }
}

/**
 * LMU configures polling of Le Mans Ultimate's local REST API (port 6397), which
 * exposes strategy/weather-forecast/pit data the rF2 shared memory does not. The
 * API is reachable from the host directly, so no sidecar is involved. When
 * Enabled, the app polls it while LMU telemetry is live and merges the result
 * into the strategy session model.
 */
export class LMU {
    "enabled": boolean;
    "base_url": string;
    "poll_hz": number;

    /** Creates a new LMU instance. */
    constructor($$source: Partial<LMU> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("poll_hz" in $$source)) {
            this["poll_hz"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LMU instance from a string or object.
     */
    static createFrom($$source: any = {}): LMU {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LMU($$parsedSource as Partial<LMU>);
    }
}

export class Moza {
    "enabled": boolean;
    "port": string;
    "update_hz": number;
    "rpm_brightness": number;
    "rpm_colors": Color[];
    "button_colors": Color[];
    "button_mask": number;

    /**
     * RPMLEDs manually sets the number of rev-light segments on the wheel rim.
     * The rim is not identifiable over USB (only the base is), so when the base's
     * default profile does not match the attached rim, set this to override it.
     * 0 means "auto" — use the detected base's profile (or the default).
     */
    "rpm_leds"?: number;

    /**
     * Protocol selects the rim's LED protocol: "" / "old" for the legacy
     * telemetry-mask rims (default, unchanged), "new" for newer rims such as the
     * ESX whose LEDs live on a separate device and need a channel-config burst, or
     * "auto" to detect at connect by querying the rim over serial (the new LED
     * controller, device 0x18, answers a model-code query; legacy rims stay
     * silent). The rim is not identifiable over USB, hence the serial probe.
     */
    "protocol"?: string;

    /**
     * RPMCurvePoints defines the rev-light response curve as control points in
     * normalised [0,1]×[0,1] space (input RPM ratio → output bar fill), drawn in
     * the dashboard as a draggable spline (photo-editor "curves" style). The
     * points are interpolated with a monotone cubic spline. Empty or fewer than
     * two points means a straight linear response (default, unchanged), so old
     * configs are unaffected. The dashboard's presets just populate these points.
     */
    "rpm_curve_points"?: CurvePoint[];

    /** Creates a new Moza instance. */
    constructor($$source: Partial<Moza> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("update_hz" in $$source)) {
            this["update_hz"] = 0;
        }
        if (!("rpm_brightness" in $$source)) {
            this["rpm_brightness"] = 0;
        }
        if (!("rpm_colors" in $$source)) {
            this["rpm_colors"] = Array.from({ length: 10 }, () => Array.from({ length: 3 }, () => 0));
        }
        if (!("button_colors" in $$source)) {
            this["button_colors"] = Array.from({ length: 10 }, () => Array.from({ length: 3 }, () => 0));
        }
        if (!("button_mask" in $$source)) {
            this["button_mask"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Moza instance from a string or object.
     */
    static createFrom($$source: any = {}): Moza {
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rpm_curve_points" in $$parsedSource) {
            $$parsedSource["rpm_curve_points"] = $$createField9_0($$parsedSource["rpm_curve_points"]);
        }
        return new Moza($$parsedSource as Partial<Moza>);
    }
}

export class Overlay {
    "enabled": boolean;
    "output"?: string;
    "game_window_match"?: string;
    "width"?: number | null;
    "height"?: number | null;
    "anchor": string;
    "margin_top"?: number | null;
    "margin_right"?: number | null;
    "margin_bottom"?: number | null;
    "margin_left"?: number | null;
    "update_hz": number;
    "opacity": number;
    "show_steering": boolean;
    "steering_image_path"?: string;
    "steering_size"?: number | null;

    /**
     * SteeringX/SteeringY position the steering wheel within the overlay box
     * (top-left origin, logical pixels). When nil they fall back to the legacy
     * auto-placement (top-right corner) — see SteeringXValue/SteeringYValue.
     */
    "steering_x"?: number | null;
    "steering_y"?: number | null;

    /**
     * SteeringRangeDeg is the lock-to-lock wheel rotation (degrees) used to map
     * the steering input to the displayed wheel angle. It is the fallback for
     * games that do not report a range (Forza); LMU reports a per-car range that
     * overrides it. 0 means "use the default".
     */
    "steering_range_deg"?: number;

    /** Creates a new Overlay instance. */
    constructor($$source: Partial<Overlay> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("anchor" in $$source)) {
            this["anchor"] = "";
        }
        if (!("update_hz" in $$source)) {
            this["update_hz"] = 0;
        }
        if (!("opacity" in $$source)) {
            this["opacity"] = 0;
        }
        if (!("show_steering" in $$source)) {
            this["show_steering"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overlay instance from a string or object.
     */
    static createFrom($$source: any = {}): Overlay {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Overlay($$parsedSource as Partial<Overlay>);
    }
}

export class Recording {
    "dir": string;

    /** Creates a new Recording instance. */
    constructor($$source: Partial<Recording> = {}) {
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recording instance from a string or object.
     */
    static createFrom($$source: any = {}): Recording {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recording($$parsedSource as Partial<Recording>);
    }
}

export class Terminal {
    "enabled": boolean;

    /** Creates a new Terminal instance. */
    constructor($$source: Partial<Terminal> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Terminal instance from a string or object.
     */
    static createFrom($$source: any = {}): Terminal {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Terminal($$parsedSource as Partial<Terminal>);
    }
}

/**
 * Voice configures the offline push-to-talk voice-command MVP (whisper.cpp STT +
 * a deterministic grammar driving LMU's pit menu over its REST API). It is
 * Linux-only for now and disabled by default. The trigger is either an external
 * FIFO that something writes "press"/"release" to (a Hyprland keybind, a wheel-
 * button script) or a configured evdev button read directly from /dev/input.
 */
export class Voice {
    "enabled": boolean;

    /**
     * WhisperBin/WhisperModel point at a local whisper.cpp build and ggml model.
     */
    "whisper_bin": string;
    "whisper_model": string;
    "language"?: string;

    /**
     * CaptureCmd optionally overrides the recorder; "{out}" is the WAV path. Empty
     * uses arecord (mono 16 kHz). Example: "parecord --file-format=wav {out}".
     */
    "capture_cmd"?: string;

    /**
     * Trigger is "fifo" (default) or "button".
     */
    "trigger"?: string;

    /**
     * FIFOPath is the named pipe for trigger=="fifo".
     */
    "fifo_path"?: string;

    /**
     * ButtonDevice/ButtonCode are the evdev device + key code for trigger=="button"
     * (populate them with the LearnVoiceButton helper rather than by hand).
     */
    "button_device"?: string;
    "button_code"?: number;

    /**
     * ConfirmSeconds is how long a staged pit change waits for an affirmation
     * ("yes") before it is dropped. 0 uses the built-in default.
     */
    "confirm_seconds"?: number;

    /** Creates a new Voice instance. */
    constructor($$source: Partial<Voice> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("whisper_bin" in $$source)) {
            this["whisper_bin"] = "";
        }
        if (!("whisper_model" in $$source)) {
            this["whisper_model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Voice instance from a string or object.
     */
    static createFrom($$source: any = {}): Voice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Voice($$parsedSource as Partial<Voice>);
    }
}

// Private type creation functions
const $$createType0 = Moza.createFrom;
const $$createType1 = Recording.createFrom;
const $$createType2 = Terminal.createFrom;
const $$createType3 = Overlay.createFrom;
const $$createType4 = LMU.createFrom;
const $$createType5 = Voice.createFrom;
const $$createType6 = CurvePoint.createFrom;
const $$createType7 = $Create.Array($$createType6);
