// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Telemetry {
    "IsRaceOn": number;
    "TimestampMS": number;
    "EngineMaxRpm": number;
    "EngineIdleRpm": number;
    "CurrentEngineRpm": number;
    "AccelerationX": number;
    "AccelerationY": number;
    "AccelerationZ": number;
    "VelocityX": number;
    "VelocityY": number;
    "VelocityZ": number;
    "AngularVelocityX": number;
    "AngularVelocityY": number;
    "AngularVelocityZ": number;
    "Yaw": number;
    "Pitch": number;
    "Roll": number;
    "NormalizedSuspensionTravelFrontLeft": number;
    "NormalizedSuspensionTravelFrontRight": number;
    "NormalizedSuspensionTravelRearLeft": number;
    "NormalizedSuspensionTravelRearRight": number;
    "TireSlipRatioFrontLeft": number;
    "TireSlipRatioFrontRight": number;
    "TireSlipRatioRearLeft": number;
    "TireSlipRatioRearRight": number;
    "WheelRotationSpeedFrontLeft": number;
    "WheelRotationSpeedFrontRight": number;
    "WheelRotationSpeedRearLeft": number;
    "WheelRotationSpeedRearRight": number;
    "WheelOnRumbleStripFrontLeft": number;
    "WheelOnRumbleStripFrontRight": number;
    "WheelOnRumbleStripRearLeft": number;
    "WheelOnRumbleStripRearRight": number;
    "WheelInPuddleFrontLeft": number;
    "WheelInPuddleFrontRight": number;
    "WheelInPuddleRearLeft": number;
    "WheelInPuddleRearRight": number;
    "SurfaceRumbleFrontLeft": number;
    "SurfaceRumbleFrontRight": number;
    "SurfaceRumbleRearLeft": number;
    "SurfaceRumbleRearRight": number;
    "TireSlipAngleFrontLeft": number;
    "TireSlipAngleFrontRight": number;
    "TireSlipAngleRearLeft": number;
    "TireSlipAngleRearRight": number;
    "TireCombinedSlipFrontLeft": number;
    "TireCombinedSlipFrontRight": number;
    "TireCombinedSlipRearLeft": number;
    "TireCombinedSlipRearRight": number;
    "SuspensionTravelMetersFrontLeft": number;
    "SuspensionTravelMetersFrontRight": number;
    "SuspensionTravelMetersRearLeft": number;
    "SuspensionTravelMetersRearRight": number;
    "CarOrdinal": number;
    "CarClass": number;
    "CarPerformanceIndex": number;
    "DrivetrainType": number;
    "NumCylinders": number;
    "CarGroup": number;
    "SmashableVelDiff": number;
    "SmashableMass": number;
    "PositionX": number;
    "PositionY": number;
    "PositionZ": number;
    "Speed": number;
    "Power": number;
    "Torque": number;
    "TireTempFrontLeft": number;
    "TireTempFrontRight": number;
    "TireTempRearLeft": number;
    "TireTempRearRight": number;
    "Boost": number;
    "Fuel": number;
    "DistanceTraveled": number;
    "BestLap": number;
    "LastLap": number;
    "CurrentLap": number;
    "CurrentRaceTime": number;
    "LapNumber": number;
    "RacePosition": number;
    "Accel": number;
    "Brake": number;
    "Clutch": number;
    "HandBrake": number;
    "Gear": number;
    "Steer": number;
    "NormalizedDrivingLine": number;
    "NormalizedAIBrakeDifference": number;

    /** Creates a new Telemetry instance. */
    constructor($$source: Partial<Telemetry> = {}) {
        if (!("IsRaceOn" in $$source)) {
            this["IsRaceOn"] = 0;
        }
        if (!("TimestampMS" in $$source)) {
            this["TimestampMS"] = 0;
        }
        if (!("EngineMaxRpm" in $$source)) {
            this["EngineMaxRpm"] = 0;
        }
        if (!("EngineIdleRpm" in $$source)) {
            this["EngineIdleRpm"] = 0;
        }
        if (!("CurrentEngineRpm" in $$source)) {
            this["CurrentEngineRpm"] = 0;
        }
        if (!("AccelerationX" in $$source)) {
            this["AccelerationX"] = 0;
        }
        if (!("AccelerationY" in $$source)) {
            this["AccelerationY"] = 0;
        }
        if (!("AccelerationZ" in $$source)) {
            this["AccelerationZ"] = 0;
        }
        if (!("VelocityX" in $$source)) {
            this["VelocityX"] = 0;
        }
        if (!("VelocityY" in $$source)) {
            this["VelocityY"] = 0;
        }
        if (!("VelocityZ" in $$source)) {
            this["VelocityZ"] = 0;
        }
        if (!("AngularVelocityX" in $$source)) {
            this["AngularVelocityX"] = 0;
        }
        if (!("AngularVelocityY" in $$source)) {
            this["AngularVelocityY"] = 0;
        }
        if (!("AngularVelocityZ" in $$source)) {
            this["AngularVelocityZ"] = 0;
        }
        if (!("Yaw" in $$source)) {
            this["Yaw"] = 0;
        }
        if (!("Pitch" in $$source)) {
            this["Pitch"] = 0;
        }
        if (!("Roll" in $$source)) {
            this["Roll"] = 0;
        }
        if (!("NormalizedSuspensionTravelFrontLeft" in $$source)) {
            this["NormalizedSuspensionTravelFrontLeft"] = 0;
        }
        if (!("NormalizedSuspensionTravelFrontRight" in $$source)) {
            this["NormalizedSuspensionTravelFrontRight"] = 0;
        }
        if (!("NormalizedSuspensionTravelRearLeft" in $$source)) {
            this["NormalizedSuspensionTravelRearLeft"] = 0;
        }
        if (!("NormalizedSuspensionTravelRearRight" in $$source)) {
            this["NormalizedSuspensionTravelRearRight"] = 0;
        }
        if (!("TireSlipRatioFrontLeft" in $$source)) {
            this["TireSlipRatioFrontLeft"] = 0;
        }
        if (!("TireSlipRatioFrontRight" in $$source)) {
            this["TireSlipRatioFrontRight"] = 0;
        }
        if (!("TireSlipRatioRearLeft" in $$source)) {
            this["TireSlipRatioRearLeft"] = 0;
        }
        if (!("TireSlipRatioRearRight" in $$source)) {
            this["TireSlipRatioRearRight"] = 0;
        }
        if (!("WheelRotationSpeedFrontLeft" in $$source)) {
            this["WheelRotationSpeedFrontLeft"] = 0;
        }
        if (!("WheelRotationSpeedFrontRight" in $$source)) {
            this["WheelRotationSpeedFrontRight"] = 0;
        }
        if (!("WheelRotationSpeedRearLeft" in $$source)) {
            this["WheelRotationSpeedRearLeft"] = 0;
        }
        if (!("WheelRotationSpeedRearRight" in $$source)) {
            this["WheelRotationSpeedRearRight"] = 0;
        }
        if (!("WheelOnRumbleStripFrontLeft" in $$source)) {
            this["WheelOnRumbleStripFrontLeft"] = 0;
        }
        if (!("WheelOnRumbleStripFrontRight" in $$source)) {
            this["WheelOnRumbleStripFrontRight"] = 0;
        }
        if (!("WheelOnRumbleStripRearLeft" in $$source)) {
            this["WheelOnRumbleStripRearLeft"] = 0;
        }
        if (!("WheelOnRumbleStripRearRight" in $$source)) {
            this["WheelOnRumbleStripRearRight"] = 0;
        }
        if (!("WheelInPuddleFrontLeft" in $$source)) {
            this["WheelInPuddleFrontLeft"] = 0;
        }
        if (!("WheelInPuddleFrontRight" in $$source)) {
            this["WheelInPuddleFrontRight"] = 0;
        }
        if (!("WheelInPuddleRearLeft" in $$source)) {
            this["WheelInPuddleRearLeft"] = 0;
        }
        if (!("WheelInPuddleRearRight" in $$source)) {
            this["WheelInPuddleRearRight"] = 0;
        }
        if (!("SurfaceRumbleFrontLeft" in $$source)) {
            this["SurfaceRumbleFrontLeft"] = 0;
        }
        if (!("SurfaceRumbleFrontRight" in $$source)) {
            this["SurfaceRumbleFrontRight"] = 0;
        }
        if (!("SurfaceRumbleRearLeft" in $$source)) {
            this["SurfaceRumbleRearLeft"] = 0;
        }
        if (!("SurfaceRumbleRearRight" in $$source)) {
            this["SurfaceRumbleRearRight"] = 0;
        }
        if (!("TireSlipAngleFrontLeft" in $$source)) {
            this["TireSlipAngleFrontLeft"] = 0;
        }
        if (!("TireSlipAngleFrontRight" in $$source)) {
            this["TireSlipAngleFrontRight"] = 0;
        }
        if (!("TireSlipAngleRearLeft" in $$source)) {
            this["TireSlipAngleRearLeft"] = 0;
        }
        if (!("TireSlipAngleRearRight" in $$source)) {
            this["TireSlipAngleRearRight"] = 0;
        }
        if (!("TireCombinedSlipFrontLeft" in $$source)) {
            this["TireCombinedSlipFrontLeft"] = 0;
        }
        if (!("TireCombinedSlipFrontRight" in $$source)) {
            this["TireCombinedSlipFrontRight"] = 0;
        }
        if (!("TireCombinedSlipRearLeft" in $$source)) {
            this["TireCombinedSlipRearLeft"] = 0;
        }
        if (!("TireCombinedSlipRearRight" in $$source)) {
            this["TireCombinedSlipRearRight"] = 0;
        }
        if (!("SuspensionTravelMetersFrontLeft" in $$source)) {
            this["SuspensionTravelMetersFrontLeft"] = 0;
        }
        if (!("SuspensionTravelMetersFrontRight" in $$source)) {
            this["SuspensionTravelMetersFrontRight"] = 0;
        }
        if (!("SuspensionTravelMetersRearLeft" in $$source)) {
            this["SuspensionTravelMetersRearLeft"] = 0;
        }
        if (!("SuspensionTravelMetersRearRight" in $$source)) {
            this["SuspensionTravelMetersRearRight"] = 0;
        }
        if (!("CarOrdinal" in $$source)) {
            this["CarOrdinal"] = 0;
        }
        if (!("CarClass" in $$source)) {
            this["CarClass"] = 0;
        }
        if (!("CarPerformanceIndex" in $$source)) {
            this["CarPerformanceIndex"] = 0;
        }
        if (!("DrivetrainType" in $$source)) {
            this["DrivetrainType"] = 0;
        }
        if (!("NumCylinders" in $$source)) {
            this["NumCylinders"] = 0;
        }
        if (!("CarGroup" in $$source)) {
            this["CarGroup"] = 0;
        }
        if (!("SmashableVelDiff" in $$source)) {
            this["SmashableVelDiff"] = 0;
        }
        if (!("SmashableMass" in $$source)) {
            this["SmashableMass"] = 0;
        }
        if (!("PositionX" in $$source)) {
            this["PositionX"] = 0;
        }
        if (!("PositionY" in $$source)) {
            this["PositionY"] = 0;
        }
        if (!("PositionZ" in $$source)) {
            this["PositionZ"] = 0;
        }
        if (!("Speed" in $$source)) {
            this["Speed"] = 0;
        }
        if (!("Power" in $$source)) {
            this["Power"] = 0;
        }
        if (!("Torque" in $$source)) {
            this["Torque"] = 0;
        }
        if (!("TireTempFrontLeft" in $$source)) {
            this["TireTempFrontLeft"] = 0;
        }
        if (!("TireTempFrontRight" in $$source)) {
            this["TireTempFrontRight"] = 0;
        }
        if (!("TireTempRearLeft" in $$source)) {
            this["TireTempRearLeft"] = 0;
        }
        if (!("TireTempRearRight" in $$source)) {
            this["TireTempRearRight"] = 0;
        }
        if (!("Boost" in $$source)) {
            this["Boost"] = 0;
        }
        if (!("Fuel" in $$source)) {
            this["Fuel"] = 0;
        }
        if (!("DistanceTraveled" in $$source)) {
            this["DistanceTraveled"] = 0;
        }
        if (!("BestLap" in $$source)) {
            this["BestLap"] = 0;
        }
        if (!("LastLap" in $$source)) {
            this["LastLap"] = 0;
        }
        if (!("CurrentLap" in $$source)) {
            this["CurrentLap"] = 0;
        }
        if (!("CurrentRaceTime" in $$source)) {
            this["CurrentRaceTime"] = 0;
        }
        if (!("LapNumber" in $$source)) {
            this["LapNumber"] = 0;
        }
        if (!("RacePosition" in $$source)) {
            this["RacePosition"] = 0;
        }
        if (!("Accel" in $$source)) {
            this["Accel"] = 0;
        }
        if (!("Brake" in $$source)) {
            this["Brake"] = 0;
        }
        if (!("Clutch" in $$source)) {
            this["Clutch"] = 0;
        }
        if (!("HandBrake" in $$source)) {
            this["HandBrake"] = 0;
        }
        if (!("Gear" in $$source)) {
            this["Gear"] = 0;
        }
        if (!("Steer" in $$source)) {
            this["Steer"] = 0;
        }
        if (!("NormalizedDrivingLine" in $$source)) {
            this["NormalizedDrivingLine"] = 0;
        }
        if (!("NormalizedAIBrakeDifference" in $$source)) {
            this["NormalizedAIBrakeDifference"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Telemetry instance from a string or object.
     */
    static createFrom($$source: any = {}): Telemetry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Telemetry($$parsedSource as Partial<Telemetry>);
    }
}
