// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * CarSetup is the player car's active setup, read from /rest/garage/summary. This
 * is data the rF2 shared memory does not expose at all — the engine's balance
 * advisory is a slip-telemetry heuristic precisely because the setup was
 * previously unavailable. Groups preserve the in-game category and setting order
 * so it reads like the garage setup sheet.
 */
export class CarSetup {
    "active_setup": string;
    "default_setup": string;
    "compare_to_setup": string;
    "track_folder": string;
    "fixed_setup_race": boolean;
    "unsaved_changes": boolean;
    "car": SetupCar;
    "groups": SetupGroup[];

    /** Creates a new CarSetup instance. */
    constructor($$source: Partial<CarSetup> = {}) {
        if (!("active_setup" in $$source)) {
            this["active_setup"] = "";
        }
        if (!("default_setup" in $$source)) {
            this["default_setup"] = "";
        }
        if (!("compare_to_setup" in $$source)) {
            this["compare_to_setup"] = "";
        }
        if (!("track_folder" in $$source)) {
            this["track_folder"] = "";
        }
        if (!("fixed_setup_race" in $$source)) {
            this["fixed_setup_race"] = false;
        }
        if (!("unsaved_changes" in $$source)) {
            this["unsaved_changes"] = false;
        }
        if (!("car" in $$source)) {
            this["car"] = (new SetupCar());
        }
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CarSetup instance from a string or object.
     */
    static createFrom($$source: any = {}): CarSetup {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("car" in $$parsedSource) {
            $$parsedSource["car"] = $$createField6_0($$parsedSource["car"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField7_0($$parsedSource["groups"]);
        }
        return new CarSetup($$parsedSource as Partial<CarSetup>);
    }
}

/**
 * ForecastNode is one weather-forecast point: a session phase (e.g. "PRACTICE")
 * and a node along it ("FINISH", "NODE_25"…) with the predicted conditions. It
 * is the flattened form of /rest/sessions/weather's nested map, so the frontend
 * gets a simple list. Values keys are the WNV_* names (WNV_RAIN_CHANCE,
 * WNV_TEMPERATURE, WNV_SKY, WNV_WINDSPEED, …).
 */
export class ForecastNode {
    "session": string;
    "node": string;
    "values": { [_ in string]?: ForecastValue };

    /** Creates a new ForecastNode instance. */
    constructor($$source: Partial<ForecastNode> = {}) {
        if (!("session" in $$source)) {
            this["session"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("values" in $$source)) {
            this["values"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForecastNode instance from a string or object.
     */
    static createFrom($$source: any = {}): ForecastNode {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField2_0($$parsedSource["values"]);
        }
        return new ForecastNode($$parsedSource as Partial<ForecastNode>);
    }
}

/**
 * ForecastValue is one forecast field, with both the numeric value and the
 * game's pre-formatted display string (e.g. {54, "54%"} or {1, "Light Clouds"}).
 */
export class ForecastValue {
    "currentValue": number;
    "stringValue": string;

    /** Creates a new ForecastValue instance. */
    constructor($$source: Partial<ForecastValue> = {}) {
        if (!("currentValue" in $$source)) {
            this["currentValue"] = 0;
        }
        if (!("stringValue" in $$source)) {
            this["stringValue"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForecastValue instance from a string or object.
     */
    static createFrom($$source: any = {}): ForecastValue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForecastValue($$parsedSource as Partial<ForecastValue>);
    }
}

/**
 * GameState mirrors /rest/sessions/GetGameState in an active session. The same
 * endpoint returns the unavailable shape (below) outside a session.
 */
export class GameState {
    "MultiStintState": string;
    "PitState": string;
    "PitEntryDist": number;
    "gamePhase": string;
    "timeOfDay": number;
    "inControlOfVehicle": boolean;
    "inMonitor": boolean;
    "isReplayActive": boolean;
    "playerVehicleLoaded": boolean;
    "raceFinished": boolean;
    "teamVehicleState": string;

    /** Creates a new GameState instance. */
    constructor($$source: Partial<GameState> = {}) {
        if (!("MultiStintState" in $$source)) {
            this["MultiStintState"] = "";
        }
        if (!("PitState" in $$source)) {
            this["PitState"] = "";
        }
        if (!("PitEntryDist" in $$source)) {
            this["PitEntryDist"] = 0;
        }
        if (!("gamePhase" in $$source)) {
            this["gamePhase"] = "";
        }
        if (!("timeOfDay" in $$source)) {
            this["timeOfDay"] = 0;
        }
        if (!("inControlOfVehicle" in $$source)) {
            this["inControlOfVehicle"] = false;
        }
        if (!("inMonitor" in $$source)) {
            this["inMonitor"] = false;
        }
        if (!("isReplayActive" in $$source)) {
            this["isReplayActive"] = false;
        }
        if (!("playerVehicleLoaded" in $$source)) {
            this["playerVehicleLoaded"] = false;
        }
        if (!("raceFinished" in $$source)) {
            this["raceFinished"] = false;
        }
        if (!("teamVehicleState" in $$source)) {
            this["teamVehicleState"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameState instance from a string or object.
     */
    static createFrom($$source: any = {}): GameState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameState($$parsedSource as Partial<GameState>);
    }
}

/**
 * PitEstimate mirrors /rest/strategy/pitstop-estimate: the projected pit-stop
 * duration broken down by activity, in seconds.
 */
export class PitEstimate {
    "fuel": number;
    "tires": number;
    "brakes": number;
    "brakeDucts": number;
    "damage": number;
    "driverSwap": number;
    "penalties": number;
    "ve": number;
    "total": number;

    /** Creates a new PitEstimate instance. */
    constructor($$source: Partial<PitEstimate> = {}) {
        if (!("fuel" in $$source)) {
            this["fuel"] = 0;
        }
        if (!("tires" in $$source)) {
            this["tires"] = 0;
        }
        if (!("brakes" in $$source)) {
            this["brakes"] = 0;
        }
        if (!("brakeDucts" in $$source)) {
            this["brakeDucts"] = 0;
        }
        if (!("damage" in $$source)) {
            this["damage"] = 0;
        }
        if (!("driverSwap" in $$source)) {
            this["driverSwap"] = 0;
        }
        if (!("penalties" in $$source)) {
            this["penalties"] = 0;
        }
        if (!("ve" in $$source)) {
            this["ve"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PitEstimate instance from a string or object.
     */
    static createFrom($$source: any = {}): PitEstimate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PitEstimate($$parsedSource as Partial<PitEstimate>);
    }
}

/**
 * PitMenuItem is one row of the in-game pit menu (/rest/garage/PitMenu/
 * receivePitMenu): a setting name, its current/default index, and the list of
 * selectable option labels (e.g. the VIRTUAL ENERGY rows "31% 6 laps").
 * 
 * The JSON tags are the clean shape sent OUT to the frontend; the game's own wire
 * keys ("PMC Value", "currentSetting", settings-as-{text}-objects) are read by the
 * custom UnmarshalJSON below, so the input keys and these output tags are decoupled.
 */
export class PitMenuItem {
    "name": string;
    "pmc": number;
    "current_setting": number;
    "default": number;
    "settings": string[];

    /** Creates a new PitMenuItem instance. */
    constructor($$source: Partial<PitMenuItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("pmc" in $$source)) {
            this["pmc"] = 0;
        }
        if (!("current_setting" in $$source)) {
            this["current_setting"] = 0;
        }
        if (!("default" in $$source)) {
            this["default"] = 0;
        }
        if (!("settings" in $$source)) {
            this["settings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PitMenuItem instance from a string or object.
     */
    static createFrom($$source: any = {}): PitMenuItem {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField4_0($$parsedSource["settings"]);
        }
        return new PitMenuItem($$parsedSource as Partial<PitMenuItem>);
    }
}

/**
 * SetupCar identifies the car the setup belongs to.
 */
export class SetupCar {
    "name": string;
    "display_name": string;
    "manufacturer": string;
    "engine": string;

    /**
     * the model tree path (e.g. "WEC 2026, GT3, Porsche 911 GT3 R LMGT3")
     */
    "class": string;

    /** Creates a new SetupCar instance. */
    constructor($$source: Partial<SetupCar> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("manufacturer" in $$source)) {
            this["manufacturer"] = "";
        }
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("class" in $$source)) {
            this["class"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupCar instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupCar {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupCar($$parsedSource as Partial<SetupCar>);
    }
}

/**
 * SetupFile is one saved setup from /rest/garage/setup (the list of saveable
 * setups for the current car). Names ending in "\" are track folders.
 */
export class SetupFile {
    "name": string;
    "created": string;
    "modified": string;
    "numDiffUpgrades": number;
    "sameVehicleClass": boolean;

    /** Creates a new SetupFile instance. */
    constructor($$source: Partial<SetupFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("modified" in $$source)) {
            this["modified"] = "";
        }
        if (!("numDiffUpgrades" in $$source)) {
            this["numDiffUpgrades"] = 0;
        }
        if (!("sameVehicleClass" in $$source)) {
            this["sameVehicleClass"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupFile instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupFile($$parsedSource as Partial<SetupFile>);
    }
}

/**
 * SetupGroup is one category of settings (e.g. "SUSPENSION_FRONT").
 */
export class SetupGroup {
    "category": string;
    "settings": SetupSetting[];

    /** Creates a new SetupGroup instance. */
    constructor($$source: Partial<SetupGroup> = {}) {
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("settings" in $$source)) {
            this["settings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupGroup {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField1_0($$parsedSource["settings"]);
        }
        return new SetupGroup($$parsedSource as Partial<SetupGroup>);
    }
}

/**
 * SetupSetting is one adjustable setting. StringValue is the in-game display
 * (e.g. "50.0:50.0", "9 (Understeer)"); Value is the raw step index. LastSaved
 * differs from StringValue when the current value has unsaved changes.
 */
export class SetupSetting {
    "key": string;
    "caption": string;
    "string_value": string;
    "value": number;
    "min_value": number;
    "max_value": number;
    "last_saved": string;

    /**
     * current value differs from the last saved one
     */
    "changed": boolean;

    /** Creates a new SetupSetting instance. */
    constructor($$source: Partial<SetupSetting> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("caption" in $$source)) {
            this["caption"] = "";
        }
        if (!("string_value" in $$source)) {
            this["string_value"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("min_value" in $$source)) {
            this["min_value"] = 0;
        }
        if (!("max_value" in $$source)) {
            this["max_value"] = 0;
        }
        if (!("last_saved" in $$source)) {
            this["last_saved"] = "";
        }
        if (!("changed" in $$source)) {
            this["changed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupSetting instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupSetting {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupSetting($$parsedSource as Partial<SetupSetting>);
    }
}

/**
 * Snapshot is one aggregated read of the LMU REST API. Available is false when
 * the game is not in an active session (Reason explains why), in which case the
 * data sections are nil. Each section is a pointer/slice/map so "absent" is
 * distinguishable from "present but zero".
 */
export class Snapshot {
    "fetched_at": time$0.Time;
    "available": boolean;
    "reason"?: string;
    "game_state"?: GameState | null;
    "pit_estimate"?: PitEstimate | null;
    "usage"?: { [_ in string]?: UsageEntry[] };
    "condition"?: VehicleCondition | null;
    "forecast"?: ForecastNode[];
    "standings"?: Standing[];
    "pit_menu"?: PitMenuItem[];

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("fetched_at" in $$source)) {
            this["fetched_at"] = null;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType11;
        const $$createField5_0 = $$createType14;
        const $$createField6_0 = $$createType16;
        const $$createField7_0 = $$createType18;
        const $$createField8_0 = $$createType20;
        const $$createField9_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("game_state" in $$parsedSource) {
            $$parsedSource["game_state"] = $$createField3_0($$parsedSource["game_state"]);
        }
        if ("pit_estimate" in $$parsedSource) {
            $$parsedSource["pit_estimate"] = $$createField4_0($$parsedSource["pit_estimate"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField5_0($$parsedSource["usage"]);
        }
        if ("condition" in $$parsedSource) {
            $$parsedSource["condition"] = $$createField6_0($$parsedSource["condition"]);
        }
        if ("forecast" in $$parsedSource) {
            $$parsedSource["forecast"] = $$createField7_0($$parsedSource["forecast"]);
        }
        if ("standings" in $$parsedSource) {
            $$parsedSource["standings"] = $$createField8_0($$parsedSource["standings"]);
        }
        if ("pit_menu" in $$parsedSource) {
            $$parsedSource["pit_menu"] = $$createField9_0($$parsedSource["pit_menu"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

/**
 * Standing is one car's row from /rest/watch/standings — a subset of the ~65
 * fields, picking the strategy-relevant ones. FuelFraction/VEFraction are 0..1.
 */
export class Standing {
    "slotID": number;
    "driverName": string;
    "carNumber": string;
    "carClass": string;
    "fullTeamName": string;
    "vehicleName": string;
    "position": number;
    "bestLapTime": number;
    "lastLapTime": number;
    "estimatedLapTime": number;
    "timeBehindLeader": number;
    "timeBehindNext": number;
    "lapsCompleted": number;
    "fuelFraction": number;
    "veFraction": number;
    "pitstops": number;
    "penalties": number;
    "pitState": string;
    "pitting": boolean;
    "inGarageStall": boolean;
    "flag": string;

    /** Creates a new Standing instance. */
    constructor($$source: Partial<Standing> = {}) {
        if (!("slotID" in $$source)) {
            this["slotID"] = 0;
        }
        if (!("driverName" in $$source)) {
            this["driverName"] = "";
        }
        if (!("carNumber" in $$source)) {
            this["carNumber"] = "";
        }
        if (!("carClass" in $$source)) {
            this["carClass"] = "";
        }
        if (!("fullTeamName" in $$source)) {
            this["fullTeamName"] = "";
        }
        if (!("vehicleName" in $$source)) {
            this["vehicleName"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }
        if (!("bestLapTime" in $$source)) {
            this["bestLapTime"] = 0;
        }
        if (!("lastLapTime" in $$source)) {
            this["lastLapTime"] = 0;
        }
        if (!("estimatedLapTime" in $$source)) {
            this["estimatedLapTime"] = 0;
        }
        if (!("timeBehindLeader" in $$source)) {
            this["timeBehindLeader"] = 0;
        }
        if (!("timeBehindNext" in $$source)) {
            this["timeBehindNext"] = 0;
        }
        if (!("lapsCompleted" in $$source)) {
            this["lapsCompleted"] = 0;
        }
        if (!("fuelFraction" in $$source)) {
            this["fuelFraction"] = 0;
        }
        if (!("veFraction" in $$source)) {
            this["veFraction"] = 0;
        }
        if (!("pitstops" in $$source)) {
            this["pitstops"] = 0;
        }
        if (!("penalties" in $$source)) {
            this["penalties"] = 0;
        }
        if (!("pitState" in $$source)) {
            this["pitState"] = "";
        }
        if (!("pitting" in $$source)) {
            this["pitting"] = false;
        }
        if (!("inGarageStall" in $$source)) {
            this["inGarageStall"] = false;
        }
        if (!("flag" in $$source)) {
            this["flag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Standing instance from a string or object.
     */
    static createFrom($$source: any = {}): Standing {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Standing($$parsedSource as Partial<Standing>);
    }
}

/**
 * UsageEntry is one stint's projected resource usage for a driver, from
 * /rest/strategy/usage (keyed by driver name → list of stints). Fuel/Tyres are
 * only populated for the player's own car. VE is virtual energy (the hypercar
 * hybrid budget), 0..1.
 */
export class UsageEntry {
    "lap": number;
    "stint": number;
    "pit": boolean;
    "ve": number;
    "fuel": number;
    "tyres": number[];

    /** Creates a new UsageEntry instance. */
    constructor($$source: Partial<UsageEntry> = {}) {
        if (!("lap" in $$source)) {
            this["lap"] = 0;
        }
        if (!("stint" in $$source)) {
            this["stint"] = 0;
        }
        if (!("pit" in $$source)) {
            this["pit"] = false;
        }
        if (!("ve" in $$source)) {
            this["ve"] = 0;
        }
        if (!("fuel" in $$source)) {
            this["fuel"] = 0;
        }
        if (!("tyres" in $$source)) {
            this["tyres"] = Array.from({ length: 4 }, () => 0);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageEntry($$parsedSource as Partial<UsageEntry>);
    }
}

/**
 * VehicleCondition mirrors /rest/garage/getVehicleCondition: the player car's
 * consumables and damage. fuelCapacity is the tank size, which the shared-memory
 * telemetry does not expose. Conditions are 0..1 (1 = fresh/undamaged).
 */
export class VehicleCondition {
    "fuel": number;
    "fuelCapacity": number;
    "tireCondition": number[];
    "brakeCondition": number[];
    "suspensionDamage": number[];
    "vehicleDamage": number;

    /** Creates a new VehicleCondition instance. */
    constructor($$source: Partial<VehicleCondition> = {}) {
        if (!("fuel" in $$source)) {
            this["fuel"] = 0;
        }
        if (!("fuelCapacity" in $$source)) {
            this["fuelCapacity"] = 0;
        }
        if (!("tireCondition" in $$source)) {
            this["tireCondition"] = Array.from({ length: 4 }, () => 0);
        }
        if (!("brakeCondition" in $$source)) {
            this["brakeCondition"] = Array.from({ length: 4 }, () => 0);
        }
        if (!("suspensionDamage" in $$source)) {
            this["suspensionDamage"] = Array.from({ length: 4 }, () => 0);
        }
        if (!("vehicleDamage" in $$source)) {
            this["vehicleDamage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VehicleCondition instance from a string or object.
     */
    static createFrom($$source: any = {}): VehicleCondition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VehicleCondition($$parsedSource as Partial<VehicleCondition>);
    }
}

// Private type creation functions
const $$createType0 = SetupCar.createFrom;
const $$createType1 = SetupGroup.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ForecastValue.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = SetupSetting.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = GameState.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = PitEstimate.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = UsageEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $$createType13);
const $$createType15 = VehicleCondition.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = ForecastNode.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = Standing.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = PitMenuItem.createFrom;
const $$createType22 = $Create.Array($$createType21);
