// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Button identifies a learned evdev button: the device node and the key code,
 * plus the device's human name for display.
 */
export class Button {
    "device": string;
    "code": number;
    "name": string;

    /** Creates a new Button instance. */
    constructor($$source: Partial<Button> = {}) {
        if (!("device" in $$source)) {
            this["device"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Button instance from a string or object.
     */
    static createFrom($$source: any = {}): Button {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Button($$parsedSource as Partial<Button>);
    }
}
