// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BalanceState is the heuristic chassis-balance read for the player car: whether
 * it tends to understeer or oversteer through corners, and an advisory proposal.
 * It is a HEURISTIC from grip/slip telemetry, not a setup readout (LMU doesn't
 * expose the setup), so it suggests a direction, never exact values.
 */
export class BalanceState {
    /**
     * cornering frames observed (0 = not enough data)
     */
    "samples": number;

    /**
     * -1 (oversteer) .. +1 (understeer)
     */
    "bias": number;

    /**
     * "Understeer" | "Neutral" | "Oversteer" | ""
     */
    "verdict": string;

    /**
     * advisory text
     */
    "proposal": string;

    /** Creates a new BalanceState instance. */
    constructor($$source: Partial<BalanceState> = {}) {
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("bias" in $$source)) {
            this["bias"] = 0;
        }
        if (!("verdict" in $$source)) {
            this["verdict"] = "";
        }
        if (!("proposal" in $$source)) {
            this["proposal"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BalanceState instance from a string or object.
     */
    static createFrom($$source: any = {}): BalanceState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BalanceState($$parsedSource as Partial<BalanceState>);
    }
}

/**
 * CarState is one car's strategy-relevant state. Every field is filled from the
 * current frame; nothing here requires history. Fuel/battery are read per car —
 * the sidecar reads the telemetry buffer for the whole grid, so rivals' values
 * are populated too (0 when the game doesn't expose them).
 */
export class CarState {
    /**
     * stable slot ID
     */
    "id": number;

    /**
     * car number — not exposed by LMU yet; UI falls back to Place
     */
    "number": string;

    /**
     * driver name
     */
    "driver": string;

    /**
     * car model
     */
    "car_name": string;

    /**
     * class name — drives the dot colour
     */
    "class": string;

    /**
     * 1-based overall position
     */
    "place": number;

    /**
     * 0..1 position around the lap — drives the circle
     */
    "lap_dist_frac": number;

    /**
     * laps completed
     */
    "total_laps": number;

    /**
     * currently in the pit lane
     */
    "in_pits": boolean;

    /**
     * 0=none,1=request,2=entering,3=stopped,4=exiting
     */
    "pit_state": number;

    /**
     * stops completed
     */
    "num_pitstops": number;

    /**
     * seconds behind the leader
     */
    "gap_to_leader": number;

    /**
     * seconds behind the car ahead
     */
    "gap_to_next": number;

    /**
     * laps down to the leader
     */
    "laps_behind_leader": number;

    /**
     * session best lap (s, 0 if none)
     */
    "best_lap": number;

    /**
     * previous lap time (s, 0 if none)
     */
    "last_lap": number;

    /**
     * current mini-sector index (rF2: 0=S3,1=S1,2=S2)
     */
    "cur_sector": number;

    /**
     * liters remaining
     */
    "fuel": number;

    /**
     * tank size (liters)
     */
    "fuel_capacity": number;

    /**
     * hybrid charge 0..1
     */
    "battery": number;

    /**
     * FL, FR, RL, RR
     */
    "tires": TireState[];

    /**
     * this is the car we're engineering for
     */
    "is_player": boolean;

    /**
     * MiniSectors / LapInProgress are the per-corner accumulation from the live
     * engine (engineer/lapaccum.go). MiniSectors (the last COMPLETED lap) is
     * filled for EVERY car so Driver Vs. can compare any rival; LapInProgress (the
     * lap currently being driven) is the player car only. Both are nil until the
     * relevant lap exists.
     */
    "mini_sectors": MiniSectorState[];
    "lap_in_progress": MiniSectorState[];

    /**
     * LapPath is the driven line (world X/Z) of the last completed lap, for the
     * Drive Line view. Captured for the player and the selected compare car only
     * (it's heavy); nil otherwise.
     */
    "lap_path": Vec2[];

    /**
     * Best* hold the fastest FULL lap the engine has seen for this car — the
     * reference the Coaching and Driver Vs. views compare against. BestSectors is
     * filled for every car; BestPath only for the player + selected compare car.
     */
    "best_sectors": MiniSectorState[];
    "best_path": Vec2[];

    /**
     * engine-measured best lap time (s)
     */
    "best_measured": number;

    /** Creates a new CarState instance. */
    constructor($$source: Partial<CarState> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("car_name" in $$source)) {
            this["car_name"] = "";
        }
        if (!("class" in $$source)) {
            this["class"] = "";
        }
        if (!("place" in $$source)) {
            this["place"] = 0;
        }
        if (!("lap_dist_frac" in $$source)) {
            this["lap_dist_frac"] = 0;
        }
        if (!("total_laps" in $$source)) {
            this["total_laps"] = 0;
        }
        if (!("in_pits" in $$source)) {
            this["in_pits"] = false;
        }
        if (!("pit_state" in $$source)) {
            this["pit_state"] = 0;
        }
        if (!("num_pitstops" in $$source)) {
            this["num_pitstops"] = 0;
        }
        if (!("gap_to_leader" in $$source)) {
            this["gap_to_leader"] = 0;
        }
        if (!("gap_to_next" in $$source)) {
            this["gap_to_next"] = 0;
        }
        if (!("laps_behind_leader" in $$source)) {
            this["laps_behind_leader"] = 0;
        }
        if (!("best_lap" in $$source)) {
            this["best_lap"] = 0;
        }
        if (!("last_lap" in $$source)) {
            this["last_lap"] = 0;
        }
        if (!("cur_sector" in $$source)) {
            this["cur_sector"] = 0;
        }
        if (!("fuel" in $$source)) {
            this["fuel"] = 0;
        }
        if (!("fuel_capacity" in $$source)) {
            this["fuel_capacity"] = 0;
        }
        if (!("battery" in $$source)) {
            this["battery"] = 0;
        }
        if (!("tires" in $$source)) {
            this["tires"] = Array.from({ length: 4 }, () => (new TireState()));
        }
        if (!("is_player" in $$source)) {
            this["is_player"] = false;
        }
        if (!("mini_sectors" in $$source)) {
            this["mini_sectors"] = [];
        }
        if (!("lap_in_progress" in $$source)) {
            this["lap_in_progress"] = [];
        }
        if (!("lap_path" in $$source)) {
            this["lap_path"] = [];
        }
        if (!("best_sectors" in $$source)) {
            this["best_sectors"] = [];
        }
        if (!("best_path" in $$source)) {
            this["best_path"] = [];
        }
        if (!("best_measured" in $$source)) {
            this["best_measured"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CarState instance from a string or object.
     */
    static createFrom($$source: any = {}): CarState {
        const $$createField20_0 = $$createType1;
        const $$createField22_0 = $$createType3;
        const $$createField23_0 = $$createType3;
        const $$createField24_0 = $$createType5;
        const $$createField25_0 = $$createType3;
        const $$createField26_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tires" in $$parsedSource) {
            $$parsedSource["tires"] = $$createField20_0($$parsedSource["tires"]);
        }
        if ("mini_sectors" in $$parsedSource) {
            $$parsedSource["mini_sectors"] = $$createField22_0($$parsedSource["mini_sectors"]);
        }
        if ("lap_in_progress" in $$parsedSource) {
            $$parsedSource["lap_in_progress"] = $$createField23_0($$parsedSource["lap_in_progress"]);
        }
        if ("lap_path" in $$parsedSource) {
            $$parsedSource["lap_path"] = $$createField24_0($$parsedSource["lap_path"]);
        }
        if ("best_sectors" in $$parsedSource) {
            $$parsedSource["best_sectors"] = $$createField25_0($$parsedSource["best_sectors"]);
        }
        if ("best_path" in $$parsedSource) {
            $$parsedSource["best_path"] = $$createField26_0($$parsedSource["best_path"]);
        }
        return new CarState($$parsedSource as Partial<CarState>);
    }
}

/**
 * DriverUsage is one driver's projected resource usage for the current stint.
 * Fuel is only populated for the player's own car. VE is virtual energy (0..1).
 */
export class DriverUsage {
    "driver": string;
    "stint": number;
    "lap": number;
    "ve": number;
    "fuel": number;

    /** Creates a new DriverUsage instance. */
    constructor($$source: Partial<DriverUsage> = {}) {
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("stint" in $$source)) {
            this["stint"] = 0;
        }
        if (!("lap" in $$source)) {
            this["lap"] = 0;
        }
        if (!("ve" in $$source)) {
            this["ve"] = 0;
        }
        if (!("fuel" in $$source)) {
            this["fuel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DriverUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): DriverUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DriverUsage($$parsedSource as Partial<DriverUsage>);
    }
}

/**
 * FlagState is the global race-control state powering the popup banner.
 */
export class FlagState {
    "green": boolean;
    "yellow": boolean;

    /**
     * a safety car exists this session
     */
    "safety_car": boolean;

    /**
     * safety car is currently deployed
     */
    "sc_active": boolean;

    /**
     * per-sector yellow state
     */
    "sector_flags": number[];

    /** Creates a new FlagState instance. */
    constructor($$source: Partial<FlagState> = {}) {
        if (!("green" in $$source)) {
            this["green"] = false;
        }
        if (!("yellow" in $$source)) {
            this["yellow"] = false;
        }
        if (!("safety_car" in $$source)) {
            this["safety_car"] = false;
        }
        if (!("sc_active" in $$source)) {
            this["sc_active"] = false;
        }
        if (!("sector_flags" in $$source)) {
            this["sector_flags"] = Array.from({ length: 3 }, () => 0);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlagState instance from a string or object.
     */
    static createFrom($$source: any = {}): FlagState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlagState($$parsedSource as Partial<FlagState>);
    }
}

/**
 * ForecastPoint is the predicted weather at one session node.
 */
export class ForecastPoint {
    /**
     * session phase ("PRACTICE", "RACE", …)
     */
    "session": string;

    /**
     * node along it ("FINISH", "NODE_25", …)
     */
    "node": string;

    /**
     * percent
     */
    "rain_chance": number;

    /**
     * ambient, degrees
     */
    "temperature": number;

    /**
     * textual sky condition ("Light Clouds", …)
     */
    "sky": string;

    /**
     * game wind-speed units
     */
    "wind_speed": number;

    /** Creates a new ForecastPoint instance. */
    constructor($$source: Partial<ForecastPoint> = {}) {
        if (!("session" in $$source)) {
            this["session"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("rain_chance" in $$source)) {
            this["rain_chance"] = 0;
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }
        if (!("sky" in $$source)) {
            this["sky"] = "";
        }
        if (!("wind_speed" in $$source)) {
            this["wind_speed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForecastPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): ForecastPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForecastPoint($$parsedSource as Partial<ForecastPoint>);
    }
}

/**
 * MiniSectorState is the resource usage accumulated across one mini-sector (one
 * of numMiniSectors equal slices of the lap). It is what lets the engineer say
 * "you used too much tire braking into this corner". All deltas are over the
 * mini-sector only.
 */
export class MiniSectorState {
    /**
     * 0..numMiniSectors-1
     */
    "index": number;

    /**
     * wear consumed per wheel (entry-exit; see lapaccum.go)
     */
    "tire_wear": number[];

    /**
     * liters burned
     */
    "fuel_used": number;

    /**
     * hybrid charge delta (+ depleted, - regen)
     */
    "battery_used": number;

    /**
     * seconds spent in the mini-sector
     */
    "time_spent": number;

    /**
     * m/s at entry
     */
    "entry_speed": number;

    /**
     * m/s at exit
     */
    "exit_speed": number;

    /**
     * slowest m/s within the mini-sector
     */
    "min_speed": number;

    /** Creates a new MiniSectorState instance. */
    constructor($$source: Partial<MiniSectorState> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("tire_wear" in $$source)) {
            this["tire_wear"] = Array.from({ length: 4 }, () => 0);
        }
        if (!("fuel_used" in $$source)) {
            this["fuel_used"] = 0;
        }
        if (!("battery_used" in $$source)) {
            this["battery_used"] = 0;
        }
        if (!("time_spent" in $$source)) {
            this["time_spent"] = 0;
        }
        if (!("entry_speed" in $$source)) {
            this["entry_speed"] = 0;
        }
        if (!("exit_speed" in $$source)) {
            this["exit_speed"] = 0;
        }
        if (!("min_speed" in $$source)) {
            this["min_speed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MiniSectorState instance from a string or object.
     */
    static createFrom($$source: any = {}): MiniSectorState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MiniSectorState($$parsedSource as Partial<MiniSectorState>);
    }
}

/**
 * PitEstimate is the projected pit-stop duration broken down by activity (s).
 */
export class PitEstimate {
    "total": number;
    "fuel": number;
    "tires": number;

    /**
     * virtual-energy recharge time
     */
    "ve": number;
    "damage": number;
    "driver_swap": number;
    "penalties": number;

    /** Creates a new PitEstimate instance. */
    constructor($$source: Partial<PitEstimate> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("fuel" in $$source)) {
            this["fuel"] = 0;
        }
        if (!("tires" in $$source)) {
            this["tires"] = 0;
        }
        if (!("ve" in $$source)) {
            this["ve"] = 0;
        }
        if (!("damage" in $$source)) {
            this["damage"] = 0;
        }
        if (!("driver_swap" in $$source)) {
            this["driver_swap"] = 0;
        }
        if (!("penalties" in $$source)) {
            this["penalties"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PitEstimate instance from a string or object.
     */
    static createFrom($$source: any = {}): PitEstimate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PitEstimate($$parsedSource as Partial<PitEstimate>);
    }
}

/**
 * PitMenuEntry is one in-game pit-menu row with its currently-selected option
 * text resolved (e.g. {"VIRTUAL ENERGY:", "31% 6 laps"}).
 */
export class PitMenuEntry {
    "name": string;
    "current": string;

    /** Creates a new PitMenuEntry instance. */
    constructor($$source: Partial<PitMenuEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PitMenuEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PitMenuEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PitMenuEntry($$parsedSource as Partial<PitMenuEntry>);
    }
}

/**
 * PlayerDetail is the instantaneous "Car Management" view of the player's car:
 * powertrain, energy, aero, suspension, driver aids and damage. It is player-only
 * (the data is heavy and only the engineered car needs it) and needs no history,
 * so it is mapped straight from the current frame. Present is false until a
 * player car is identified.
 */
export class PlayerDetail {
    "present": boolean;

    /**
     * powertrain / temps
     */
    "rpm": number;
    "max_rpm": number;

    /**
     * Celsius
     */
    "water_temp": number;

    /**
     * Celsius
     */
    "oil_temp": number;

    /**
     * hybrid / electric
     * 0=unavail,1=inactive,2=propulsion,3=regen
     */
    "electric_state": number;

    /**
     * motor temp, Celsius
     */
    "electric_temp": number;

    /**
     * aero / suspension
     * Newtons
     */
    "front_downforce": number;

    /**
     * Newtons
     */
    "rear_downforce": number;

    /**
     * Newtons
     */
    "drag": number;
    "front_ride_height": number;
    "rear_ride_height": number;

    /**
     * 0..1 toward the rear
     */
    "rear_brake_bias": number;

    /**
     * driver aids (session-wide settings)
     * 0=off..3
     */
    "traction_control": number;

    /**
     * 0=off..2
     */
    "abs": number;

    /**
     * 0=off..2
     */
    "stability_control": number;

    /**
     * m/s
     */
    "pit_speed_limit": number;

    /**
     * damage: per-panel dent severity (0=none,1=minor,2=major)
     */
    "dent_severity": number[];

    /**
     * max of DentSeverity, for a quick at-a-glance level
     */
    "worst_dent": number;

    /**
     * Balance is the heuristic understeer/oversteer assessment + advisory proposal.
     */
    "balance": BalanceState;

    /** Creates a new PlayerDetail instance. */
    constructor($$source: Partial<PlayerDetail> = {}) {
        if (!("present" in $$source)) {
            this["present"] = false;
        }
        if (!("rpm" in $$source)) {
            this["rpm"] = 0;
        }
        if (!("max_rpm" in $$source)) {
            this["max_rpm"] = 0;
        }
        if (!("water_temp" in $$source)) {
            this["water_temp"] = 0;
        }
        if (!("oil_temp" in $$source)) {
            this["oil_temp"] = 0;
        }
        if (!("electric_state" in $$source)) {
            this["electric_state"] = 0;
        }
        if (!("electric_temp" in $$source)) {
            this["electric_temp"] = 0;
        }
        if (!("front_downforce" in $$source)) {
            this["front_downforce"] = 0;
        }
        if (!("rear_downforce" in $$source)) {
            this["rear_downforce"] = 0;
        }
        if (!("drag" in $$source)) {
            this["drag"] = 0;
        }
        if (!("front_ride_height" in $$source)) {
            this["front_ride_height"] = 0;
        }
        if (!("rear_ride_height" in $$source)) {
            this["rear_ride_height"] = 0;
        }
        if (!("rear_brake_bias" in $$source)) {
            this["rear_brake_bias"] = 0;
        }
        if (!("traction_control" in $$source)) {
            this["traction_control"] = 0;
        }
        if (!("abs" in $$source)) {
            this["abs"] = 0;
        }
        if (!("stability_control" in $$source)) {
            this["stability_control"] = 0;
        }
        if (!("pit_speed_limit" in $$source)) {
            this["pit_speed_limit"] = 0;
        }
        if (!("dent_severity" in $$source)) {
            this["dent_severity"] = Array.from({ length: 8 }, () => 0);
        }
        if (!("worst_dent" in $$source)) {
            this["worst_dent"] = 0;
        }
        if (!("balance" in $$source)) {
            this["balance"] = (new BalanceState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): PlayerDetail {
        const $$createField19_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("balance" in $$parsedSource) {
            $$parsedSource["balance"] = $$createField19_0($$parsedSource["balance"]);
        }
        return new PlayerDetail($$parsedSource as Partial<PlayerDetail>);
    }
}

/**
 * RaceEvent is one entry in the race timeline / popup feed: a flag change, a
 * competitor pit entry, or a notable contact. Generated by the engine from frame-
 * to-frame state transitions (engineer/events.go).
 */
export class RaceEvent {
    /**
     * session time the event happened (s)
     */
    "at_et": number;

    /**
     * "flag" | "pit" | "contact"
     */
    "kind": string;

    /**
     * car involved (-1 for session-wide)
     */
    "car_id": number;

    /**
     * human-readable, ready to display
     */
    "message": string;

    /** Creates a new RaceEvent instance. */
    constructor($$source: Partial<RaceEvent> = {}) {
        if (!("at_et" in $$source)) {
            this["at_et"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("car_id" in $$source)) {
            this["car_id"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RaceEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): RaceEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RaceEvent($$parsedSource as Partial<RaceEvent>);
    }
}

/**
 * SessionState is the complete, game-agnostic snapshot the strategy UI renders.
 * One of these is produced per observed frame. Available is false before any
 * frame has arrived (or for Forza, which produces no multi-car frame).
 */
export class SessionState {
    "available": boolean;

    /**
     * "lmu" (future: other games)
     */
    "game": string;

    /**
     * track name
     */
    "track": string;

    /**
     * meters (one lap)
     */
    "track_length": number;

    /**
     * rF2 session enum (10-13 = race)
     */
    "session_type": number;

    /**
     * elapsed session time (s)
     */
    "session_time": number;

    /**
     * scheduled end (s, 0 if lap-limited)
     */
    "session_end_time": number;

    /**
     * race lap count (0 if time-limited)
     */
    "max_laps": number;

    /**
     * slot ID of the player's car (-1 unknown)
     */
    "player_id": number;
    "flags": FlagState;
    "weather": WeatherState;
    "cars": CarState[];

    /**
     * car-management detail for the player car only
     */
    "player": PlayerDetail;

    /**
     * most-recent-last race timeline (bounded)
     */
    "events": RaceEvent[];

    /**
     * per-mini-sector corner label ("T1"/""=straight); derived from the reference lap
     */
    "corners": string[];

    /**
     * Strategy carries the extras polled from LMU's REST API (pit-stop time
     * estimate, fuel-tank capacity, weather forecast, per-driver projections) that
     * the shared-memory frame does not contain. Present is false until the API has
     * been polled in an active session. It is merged onto every snapshot (re-applied
     * each frame) so the frontend gets it alongside the per-frame state.
     */
    "strategy": StrategyState;

    /** Creates a new SessionState instance. */
    constructor($$source: Partial<SessionState> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }
        if (!("track" in $$source)) {
            this["track"] = "";
        }
        if (!("track_length" in $$source)) {
            this["track_length"] = 0;
        }
        if (!("session_type" in $$source)) {
            this["session_type"] = 0;
        }
        if (!("session_time" in $$source)) {
            this["session_time"] = 0;
        }
        if (!("session_end_time" in $$source)) {
            this["session_end_time"] = 0;
        }
        if (!("max_laps" in $$source)) {
            this["max_laps"] = 0;
        }
        if (!("player_id" in $$source)) {
            this["player_id"] = 0;
        }
        if (!("flags" in $$source)) {
            this["flags"] = (new FlagState());
        }
        if (!("weather" in $$source)) {
            this["weather"] = (new WeatherState());
        }
        if (!("cars" in $$source)) {
            this["cars"] = [];
        }
        if (!("player" in $$source)) {
            this["player"] = (new PlayerDetail());
        }
        if (!("events" in $$source)) {
            this["events"] = [];
        }
        if (!("corners" in $$source)) {
            this["corners"] = [];
        }
        if (!("strategy" in $$source)) {
            this["strategy"] = (new StrategyState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionState instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionState {
        const $$createField9_0 = $$createType7;
        const $$createField10_0 = $$createType8;
        const $$createField11_0 = $$createType10;
        const $$createField12_0 = $$createType11;
        const $$createField13_0 = $$createType13;
        const $$createField14_0 = $$createType14;
        const $$createField15_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField9_0($$parsedSource["flags"]);
        }
        if ("weather" in $$parsedSource) {
            $$parsedSource["weather"] = $$createField10_0($$parsedSource["weather"]);
        }
        if ("cars" in $$parsedSource) {
            $$parsedSource["cars"] = $$createField11_0($$parsedSource["cars"]);
        }
        if ("player" in $$parsedSource) {
            $$parsedSource["player"] = $$createField12_0($$parsedSource["player"]);
        }
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField13_0($$parsedSource["events"]);
        }
        if ("corners" in $$parsedSource) {
            $$parsedSource["corners"] = $$createField14_0($$parsedSource["corners"]);
        }
        if ("strategy" in $$parsedSource) {
            $$parsedSource["strategy"] = $$createField15_0($$parsedSource["strategy"]);
        }
        return new SessionState($$parsedSource as Partial<SessionState>);
    }
}

/**
 * StrategyState is the game-agnostic projection of the LMU REST extras. The app
 * maps the LMU-specific rest.Snapshot onto this so the engine stays decoupled
 * from the REST layer.
 */
export class StrategyState {
    "present": boolean;

    /**
     * race-control phase ("GPHASE_GREEN", …)
     */
    "game_phase": string;

    /**
     * player pit state ("EXITING", "NONE", …)
     */
    "pit_state": string;

    /**
     * tank size (liters) — authoritative from REST
     */
    "fuel_capacity": number;

    /**
     * projected next pit-stop duration
     */
    "pit_estimate": PitEstimate;

    /**
     * weather forecast across session nodes
     */
    "forecast": ForecastPoint[];

    /**
     * per-driver fuel/energy projections (all cars)
     */
    "drivers": DriverUsage[];

    /**
     * current in-game pit-menu selections
     */
    "pit_menu": PitMenuEntry[];

    /** Creates a new StrategyState instance. */
    constructor($$source: Partial<StrategyState> = {}) {
        if (!("present" in $$source)) {
            this["present"] = false;
        }
        if (!("game_phase" in $$source)) {
            this["game_phase"] = "";
        }
        if (!("pit_state" in $$source)) {
            this["pit_state"] = "";
        }
        if (!("fuel_capacity" in $$source)) {
            this["fuel_capacity"] = 0;
        }
        if (!("pit_estimate" in $$source)) {
            this["pit_estimate"] = (new PitEstimate());
        }
        if (!("forecast" in $$source)) {
            this["forecast"] = [];
        }
        if (!("drivers" in $$source)) {
            this["drivers"] = [];
        }
        if (!("pit_menu" in $$source)) {
            this["pit_menu"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StrategyState instance from a string or object.
     */
    static createFrom($$source: any = {}): StrategyState {
        const $$createField4_0 = $$createType16;
        const $$createField5_0 = $$createType18;
        const $$createField6_0 = $$createType20;
        const $$createField7_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pit_estimate" in $$parsedSource) {
            $$parsedSource["pit_estimate"] = $$createField4_0($$parsedSource["pit_estimate"]);
        }
        if ("forecast" in $$parsedSource) {
            $$parsedSource["forecast"] = $$createField5_0($$parsedSource["forecast"]);
        }
        if ("drivers" in $$parsedSource) {
            $$parsedSource["drivers"] = $$createField6_0($$parsedSource["drivers"]);
        }
        if ("pit_menu" in $$parsedSource) {
            $$parsedSource["pit_menu"] = $$createField7_0($$parsedSource["pit_menu"]);
        }
        return new StrategyState($$parsedSource as Partial<StrategyState>);
    }
}

/**
 * TireState is one corner's tire condition. Tire and brake temps are converted
 * from LMU's Kelvin to Celsius in mapCar.
 */
export class TireState {
    /**
     * left/center/right, Celsius
     */
    "temp": number[];

    /**
     * kPa
     */
    "pressure": number;

    /**
     * 0..1 (1 = fresh in rF2? treated as a fraction)
     */
    "wear": number;

    /**
     * Celsius
     */
    "brake_temp": number;

    /**
     * e.g. "Soft"
     */
    "compound": string;

    /** Creates a new TireState instance. */
    constructor($$source: Partial<TireState> = {}) {
        if (!("temp" in $$source)) {
            this["temp"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("pressure" in $$source)) {
            this["pressure"] = 0;
        }
        if (!("wear" in $$source)) {
            this["wear"] = 0;
        }
        if (!("brake_temp" in $$source)) {
            this["brake_temp"] = 0;
        }
        if (!("compound" in $$source)) {
            this["compound"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TireState instance from a string or object.
     */
    static createFrom($$source: any = {}): TireState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TireState($$parsedSource as Partial<TireState>);
    }
}

/**
 * Vec2 is a world-plane point (X east/west, Z north/south) used for the driven
 * line. Y (height) is dropped — the line is drawn top-down.
 */
export class Vec2 {
    "x": number;
    "z": number;

    /** Creates a new Vec2 instance. */
    constructor($$source: Partial<Vec2> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("z" in $$source)) {
            this["z"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Vec2 instance from a string or object.
     */
    static createFrom($$source: any = {}): Vec2 {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Vec2($$parsedSource as Partial<Vec2>);
    }
}

/**
 * WeatherState is the session weather for the Strategy Calls forecast.
 */
export class WeatherState {
    /**
     * Celsius
     */
    "ambient_temp": number;

    /**
     * Celsius
     */
    "track_temp": number;

    /**
     * 0..1 overall
     */
    "raining": number;

    /**
     * 3x3 rain intensity across the track
     */
    "rain_grid": number[];

    /**
     * m/s
     */
    "wind_max": number;

    /**
     * 0..1
     */
    "cloudiness": number;

    /** Creates a new WeatherState instance. */
    constructor($$source: Partial<WeatherState> = {}) {
        if (!("ambient_temp" in $$source)) {
            this["ambient_temp"] = 0;
        }
        if (!("track_temp" in $$source)) {
            this["track_temp"] = 0;
        }
        if (!("raining" in $$source)) {
            this["raining"] = 0;
        }
        if (!("rain_grid" in $$source)) {
            this["rain_grid"] = Array.from({ length: 9 }, () => 0);
        }
        if (!("wind_max" in $$source)) {
            this["wind_max"] = 0;
        }
        if (!("cloudiness" in $$source)) {
            this["cloudiness"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeatherState instance from a string or object.
     */
    static createFrom($$source: any = {}): WeatherState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeatherState($$parsedSource as Partial<WeatherState>);
    }
}

// Private type creation functions
const $$createType0 = TireState.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = MiniSectorState.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Vec2.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = BalanceState.createFrom;
const $$createType7 = FlagState.createFrom;
const $$createType8 = WeatherState.createFrom;
const $$createType9 = CarState.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = PlayerDetail.createFrom;
const $$createType12 = RaceEvent.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = StrategyState.createFrom;
const $$createType16 = PitEstimate.createFrom;
const $$createType17 = ForecastPoint.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = DriverUsage.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = PitMenuEntry.createFrom;
const $$createType22 = $Create.Array($$createType21);
