// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CarState is one car's strategy-relevant state. Every field is filled from the
 * current frame; nothing here requires history. Fuel/battery are read per car —
 * the sidecar reads the telemetry buffer for the whole grid, so rivals' values
 * are populated too (0 when the game doesn't expose them).
 */
export class CarState {
    /**
     * stable slot ID
     */
    "id": number;

    /**
     * car number — not exposed by LMU yet; UI falls back to Place
     */
    "number": string;

    /**
     * driver name
     */
    "driver": string;

    /**
     * car model
     */
    "car_name": string;

    /**
     * class name — drives the dot colour
     */
    "class": string;

    /**
     * 1-based overall position
     */
    "place": number;

    /**
     * 0..1 position around the lap — drives the circle
     */
    "lap_dist_frac": number;

    /**
     * laps completed
     */
    "total_laps": number;

    /**
     * currently in the pit lane
     */
    "in_pits": boolean;

    /**
     * 0=none,1=request,2=entering,3=stopped,4=exiting
     */
    "pit_state": number;

    /**
     * stops completed
     */
    "num_pitstops": number;

    /**
     * seconds behind the leader
     */
    "gap_to_leader": number;

    /**
     * seconds behind the car ahead
     */
    "gap_to_next": number;

    /**
     * laps down to the leader
     */
    "laps_behind_leader": number;

    /**
     * session best lap (s, 0 if none)
     */
    "best_lap": number;

    /**
     * previous lap time (s, 0 if none)
     */
    "last_lap": number;

    /**
     * current mini-sector index (rF2: 0=S3,1=S1,2=S2)
     */
    "cur_sector": number;

    /**
     * liters remaining
     */
    "fuel": number;

    /**
     * tank size (liters)
     */
    "fuel_capacity": number;

    /**
     * hybrid charge 0..1
     */
    "battery": number;

    /**
     * FL, FR, RL, RR
     */
    "tires": TireState[];

    /**
     * this is the car we're engineering for
     */
    "is_player": boolean;

    /** Creates a new CarState instance. */
    constructor($$source: Partial<CarState> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("car_name" in $$source)) {
            this["car_name"] = "";
        }
        if (!("class" in $$source)) {
            this["class"] = "";
        }
        if (!("place" in $$source)) {
            this["place"] = 0;
        }
        if (!("lap_dist_frac" in $$source)) {
            this["lap_dist_frac"] = 0;
        }
        if (!("total_laps" in $$source)) {
            this["total_laps"] = 0;
        }
        if (!("in_pits" in $$source)) {
            this["in_pits"] = false;
        }
        if (!("pit_state" in $$source)) {
            this["pit_state"] = 0;
        }
        if (!("num_pitstops" in $$source)) {
            this["num_pitstops"] = 0;
        }
        if (!("gap_to_leader" in $$source)) {
            this["gap_to_leader"] = 0;
        }
        if (!("gap_to_next" in $$source)) {
            this["gap_to_next"] = 0;
        }
        if (!("laps_behind_leader" in $$source)) {
            this["laps_behind_leader"] = 0;
        }
        if (!("best_lap" in $$source)) {
            this["best_lap"] = 0;
        }
        if (!("last_lap" in $$source)) {
            this["last_lap"] = 0;
        }
        if (!("cur_sector" in $$source)) {
            this["cur_sector"] = 0;
        }
        if (!("fuel" in $$source)) {
            this["fuel"] = 0;
        }
        if (!("fuel_capacity" in $$source)) {
            this["fuel_capacity"] = 0;
        }
        if (!("battery" in $$source)) {
            this["battery"] = 0;
        }
        if (!("tires" in $$source)) {
            this["tires"] = Array.from({ length: 4 }, () => (new TireState()));
        }
        if (!("is_player" in $$source)) {
            this["is_player"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CarState instance from a string or object.
     */
    static createFrom($$source: any = {}): CarState {
        const $$createField20_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tires" in $$parsedSource) {
            $$parsedSource["tires"] = $$createField20_0($$parsedSource["tires"]);
        }
        return new CarState($$parsedSource as Partial<CarState>);
    }
}

/**
 * FlagState is the global race-control state powering the popup banner.
 */
export class FlagState {
    "green": boolean;
    "yellow": boolean;

    /**
     * a safety car exists this session
     */
    "safety_car": boolean;

    /**
     * safety car is currently deployed
     */
    "sc_active": boolean;

    /**
     * per-sector yellow state
     */
    "sector_flags": number[];

    /** Creates a new FlagState instance. */
    constructor($$source: Partial<FlagState> = {}) {
        if (!("green" in $$source)) {
            this["green"] = false;
        }
        if (!("yellow" in $$source)) {
            this["yellow"] = false;
        }
        if (!("safety_car" in $$source)) {
            this["safety_car"] = false;
        }
        if (!("sc_active" in $$source)) {
            this["sc_active"] = false;
        }
        if (!("sector_flags" in $$source)) {
            this["sector_flags"] = Array.from({ length: 3 }, () => 0);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlagState instance from a string or object.
     */
    static createFrom($$source: any = {}): FlagState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlagState($$parsedSource as Partial<FlagState>);
    }
}

/**
 * SessionState is the complete, game-agnostic snapshot the strategy UI renders.
 * One of these is produced per observed frame. Available is false before any
 * frame has arrived (or for Forza, which produces no multi-car frame).
 */
export class SessionState {
    "available": boolean;

    /**
     * "lmu" (future: other games)
     */
    "game": string;

    /**
     * track name
     */
    "track": string;

    /**
     * meters (one lap)
     */
    "track_length": number;

    /**
     * rF2 session enum (10-13 = race)
     */
    "session_type": number;

    /**
     * elapsed session time (s)
     */
    "session_time": number;

    /**
     * scheduled end (s, 0 if lap-limited)
     */
    "session_end_time": number;

    /**
     * race lap count (0 if time-limited)
     */
    "max_laps": number;

    /**
     * slot ID of the player's car (-1 unknown)
     */
    "player_id": number;
    "flags": FlagState;
    "weather": WeatherState;
    "cars": CarState[];

    /** Creates a new SessionState instance. */
    constructor($$source: Partial<SessionState> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }
        if (!("track" in $$source)) {
            this["track"] = "";
        }
        if (!("track_length" in $$source)) {
            this["track_length"] = 0;
        }
        if (!("session_type" in $$source)) {
            this["session_type"] = 0;
        }
        if (!("session_time" in $$source)) {
            this["session_time"] = 0;
        }
        if (!("session_end_time" in $$source)) {
            this["session_end_time"] = 0;
        }
        if (!("max_laps" in $$source)) {
            this["max_laps"] = 0;
        }
        if (!("player_id" in $$source)) {
            this["player_id"] = 0;
        }
        if (!("flags" in $$source)) {
            this["flags"] = (new FlagState());
        }
        if (!("weather" in $$source)) {
            this["weather"] = (new WeatherState());
        }
        if (!("cars" in $$source)) {
            this["cars"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionState instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionState {
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField9_0($$parsedSource["flags"]);
        }
        if ("weather" in $$parsedSource) {
            $$parsedSource["weather"] = $$createField10_0($$parsedSource["weather"]);
        }
        if ("cars" in $$parsedSource) {
            $$parsedSource["cars"] = $$createField11_0($$parsedSource["cars"]);
        }
        return new SessionState($$parsedSource as Partial<SessionState>);
    }
}

/**
 * TireState is one corner's tire condition. Temps are Celsius (the wire format is
 * Kelvin); BrakeTemp is already Celsius.
 */
export class TireState {
    /**
     * left/center/right, Celsius
     */
    "temp": number[];

    /**
     * kPa
     */
    "pressure": number;

    /**
     * 0..1 (1 = fresh in rF2? treated as a fraction)
     */
    "wear": number;

    /**
     * Celsius
     */
    "brake_temp": number;

    /**
     * e.g. "Soft"
     */
    "compound": string;

    /** Creates a new TireState instance. */
    constructor($$source: Partial<TireState> = {}) {
        if (!("temp" in $$source)) {
            this["temp"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("pressure" in $$source)) {
            this["pressure"] = 0;
        }
        if (!("wear" in $$source)) {
            this["wear"] = 0;
        }
        if (!("brake_temp" in $$source)) {
            this["brake_temp"] = 0;
        }
        if (!("compound" in $$source)) {
            this["compound"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TireState instance from a string or object.
     */
    static createFrom($$source: any = {}): TireState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TireState($$parsedSource as Partial<TireState>);
    }
}

/**
 * WeatherState is the session weather for the Strategy Calls forecast.
 */
export class WeatherState {
    /**
     * Celsius
     */
    "ambient_temp": number;

    /**
     * Celsius
     */
    "track_temp": number;

    /**
     * 0..1 overall
     */
    "raining": number;

    /**
     * 3x3 rain intensity across the track
     */
    "rain_grid": number[];

    /**
     * m/s
     */
    "wind_max": number;

    /**
     * 0..1
     */
    "cloudiness": number;

    /** Creates a new WeatherState instance. */
    constructor($$source: Partial<WeatherState> = {}) {
        if (!("ambient_temp" in $$source)) {
            this["ambient_temp"] = 0;
        }
        if (!("track_temp" in $$source)) {
            this["track_temp"] = 0;
        }
        if (!("raining" in $$source)) {
            this["raining"] = 0;
        }
        if (!("rain_grid" in $$source)) {
            this["rain_grid"] = Array.from({ length: 9 }, () => 0);
        }
        if (!("wind_max" in $$source)) {
            this["wind_max"] = 0;
        }
        if (!("cloudiness" in $$source)) {
            this["cloudiness"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeatherState instance from a string or object.
     */
    static createFrom($$source: any = {}): WeatherState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeatherState($$parsedSource as Partial<WeatherState>);
    }
}

// Private type creation functions
const $$createType0 = TireState.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = FlagState.createFrom;
const $$createType3 = WeatherState.createFrom;
const $$createType4 = CarState.createFrom;
const $$createType5 = $Create.Array($$createType4);
