// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Event is a single detected coaching opportunity, coalesced from one or more
 * consecutive offending frames.
 */
export class Event {
    "kind": EventKind;
    "severity": Severity;
    "lap": number;

    /**
     * span start, from the start of the recording
     */
    "offset_ms": number;

    /**
     * span length (0 for instantaneous events)
     */
    "duration_ms": number;

    /**
     * location at span start
     */
    "position": Position;

    /**
     * DistanceTraveled at span start
     */
    "distance": number;

    /**
     * km/h at span start
     */
    "speed": number;

    /**
     * peak offending value (e.g. peak slip ratio)
     */
    "metric": number;

    /**
     * what happened
     */
    "message": string;

    /**
     * how to improve
     */
    "suggestion": string;

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = EventKind.$zero;
        }
        if (!("severity" in $$source)) {
            this["severity"] = Severity.$zero;
        }
        if (!("lap" in $$source)) {
            this["lap"] = 0;
        }
        if (!("offset_ms" in $$source)) {
            this["offset_ms"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }
        if (!("position" in $$source)) {
            this["position"] = (new Position());
        }
        if (!("distance" in $$source)) {
            this["distance"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("metric" in $$source)) {
            this["metric"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("suggestion" in $$source)) {
            this["suggestion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField5_0($$parsedSource["position"]);
        }
        return new Event($$parsedSource as Partial<Event>);
    }
}

/**
 * EventKind identifies the detector that produced an event.
 */
export enum EventKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindBrakeLockup = "brake_lockup",
    KindCornerWheelspin = "corner_wheelspin",
    KindUnderDriving = "under_driving",
    KindCoasting = "coasting",
    KindPedalOverlap = "pedal_overlap",
    KindOverRev = "over_rev",
    KindShortShift = "short_shift",
};

/**
 * LapScore holds the aggregate metrics for one lap (or, when Lap is -1, the
 * whole session). Percentages are 0..100; scores are 0..100 (higher is better).
 */
export class LapScore {
    "lap": number;
    "duration_ms": number;
    "sample_count": number;

    /**
     * seconds, from Forza CurrentLap; 0 if unknown
     */
    "lap_time": number;
    "wheelspin_pct": number;
    "lockup_pct": number;
    "coasting_pct": number;
    "throttle_score": number;
    "lockup_events": number;
    "wheelspin_events": number;
    "overall_score": number;

    /** Creates a new LapScore instance. */
    constructor($$source: Partial<LapScore> = {}) {
        if (!("lap" in $$source)) {
            this["lap"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }
        if (!("sample_count" in $$source)) {
            this["sample_count"] = 0;
        }
        if (!("lap_time" in $$source)) {
            this["lap_time"] = 0;
        }
        if (!("wheelspin_pct" in $$source)) {
            this["wheelspin_pct"] = 0;
        }
        if (!("lockup_pct" in $$source)) {
            this["lockup_pct"] = 0;
        }
        if (!("coasting_pct" in $$source)) {
            this["coasting_pct"] = 0;
        }
        if (!("throttle_score" in $$source)) {
            this["throttle_score"] = 0;
        }
        if (!("lockup_events" in $$source)) {
            this["lockup_events"] = 0;
        }
        if (!("wheelspin_events" in $$source)) {
            this["wheelspin_events"] = 0;
        }
        if (!("overall_score" in $$source)) {
            this["overall_score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LapScore instance from a string or object.
     */
    static createFrom($$source: any = {}): LapScore {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LapScore($$parsedSource as Partial<LapScore>);
    }
}

/**
 * Position is the world location where an event began.
 */
export class Position {
    "x": number;
    "y": number;
    "z": number;

    /** Creates a new Position instance. */
    constructor($$source: Partial<Position> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("z" in $$source)) {
            this["z"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     */
    static createFrom($$source: any = {}): Position {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position($$parsedSource as Partial<Position>);
    }
}

/**
 * Report is the full analysis result returned to the frontend.
 */
export class Report {
    "recording": string;
    "laps": LapScore[];
    "overall": LapScore;
    "events": Event[];
    "notes": string[];

    /** Creates a new Report instance. */
    constructor($$source: Partial<Report> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = "";
        }
        if (!("laps" in $$source)) {
            this["laps"] = [];
        }
        if (!("overall" in $$source)) {
            this["overall"] = (new LapScore());
        }
        if (!("events" in $$source)) {
            this["events"] = [];
        }
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     */
    static createFrom($$source: any = {}): Report {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("laps" in $$parsedSource) {
            $$parsedSource["laps"] = $$createField1_0($$parsedSource["laps"]);
        }
        if ("overall" in $$parsedSource) {
            $$parsedSource["overall"] = $$createField2_0($$parsedSource["overall"]);
        }
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField3_0($$parsedSource["events"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField4_0($$parsedSource["notes"]);
        }
        return new Report($$parsedSource as Partial<Report>);
    }
}

/**
 * Severity ranks how strongly an event deserves the driver's attention.
 */
export enum Severity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SeverityInfo = "info",
    SeverityMinor = "minor",
    SeverityMajor = "major",
};

// Private type creation functions
const $$createType0 = Position.createFrom;
const $$createType1 = LapScore.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Event.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
