// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Extended is a subset of rF2Extended: API version, the session driving aids
 * (rF2PhysicsOptions), pit speed limit, and the subscription mask the sidecar
 * uses to warn when Graphics/Weather are not subscribed.
 */
export class Extended {
    "Version": number[];
    "Is64bit": number;

    /**
     * rF2PhysicsOptions (session driving aids / assists)
     * 0 (off) - 3 (high)
     */
    "TractionControl": number;

    /**
     * 0 (off) - 2 (high)
     */
    "AntiLockBrakes": number;

    /**
     * 0 (off) - 2 (high)
     */
    "StabilityControl": number;

    /**
     * 0=off,1=up,2=down,3=all
     */
    "AutoShift": number;
    "AutoClutch": number;
    "Invulnerable": number;
    "OppositeLock": number;

    /**
     * 0 (off) - 3 (high)
     */
    "SteeringHelp": number;

    /**
     * 0 (off) - 2 (high)
     */
    "BrakingHelp": number;
    "SpinRecovery": number;
    "AutoPit": number;
    "AutoLift": number;
    "AutoBlip": number;
    "FuelMult": number;
    "TireMult": number;
    "MechFail": number;
    "AllowPitcrewPush": number;
    "RepeatShifts": number;
    "HoldClutch": number;
    "AutoReverse": number;
    "AlternateNeutral": number;

    /**
     * player vehicle under AI control
     */
    "AIControl": number;

    /**
     * m/s
     */
    "CurrentPitSpeedLimit": number;

    /**
     * active UnsubscribedBuffersMask (bit 32=Graphics, 128=Weather)
     */
    "UnsubscribedBuffersMask": number;

    /**
     * bool
     */
    "SessionStarted": number;

    /** Creates a new Extended instance. */
    constructor($$source: Partial<Extended> = {}) {
        if (!("Version" in $$source)) {
            this["Version"] = Array.from({ length: 12 }, () => 0);
        }
        if (!("Is64bit" in $$source)) {
            this["Is64bit"] = 0;
        }
        if (!("TractionControl" in $$source)) {
            this["TractionControl"] = 0;
        }
        if (!("AntiLockBrakes" in $$source)) {
            this["AntiLockBrakes"] = 0;
        }
        if (!("StabilityControl" in $$source)) {
            this["StabilityControl"] = 0;
        }
        if (!("AutoShift" in $$source)) {
            this["AutoShift"] = 0;
        }
        if (!("AutoClutch" in $$source)) {
            this["AutoClutch"] = 0;
        }
        if (!("Invulnerable" in $$source)) {
            this["Invulnerable"] = 0;
        }
        if (!("OppositeLock" in $$source)) {
            this["OppositeLock"] = 0;
        }
        if (!("SteeringHelp" in $$source)) {
            this["SteeringHelp"] = 0;
        }
        if (!("BrakingHelp" in $$source)) {
            this["BrakingHelp"] = 0;
        }
        if (!("SpinRecovery" in $$source)) {
            this["SpinRecovery"] = 0;
        }
        if (!("AutoPit" in $$source)) {
            this["AutoPit"] = 0;
        }
        if (!("AutoLift" in $$source)) {
            this["AutoLift"] = 0;
        }
        if (!("AutoBlip" in $$source)) {
            this["AutoBlip"] = 0;
        }
        if (!("FuelMult" in $$source)) {
            this["FuelMult"] = 0;
        }
        if (!("TireMult" in $$source)) {
            this["TireMult"] = 0;
        }
        if (!("MechFail" in $$source)) {
            this["MechFail"] = 0;
        }
        if (!("AllowPitcrewPush" in $$source)) {
            this["AllowPitcrewPush"] = 0;
        }
        if (!("RepeatShifts" in $$source)) {
            this["RepeatShifts"] = 0;
        }
        if (!("HoldClutch" in $$source)) {
            this["HoldClutch"] = 0;
        }
        if (!("AutoReverse" in $$source)) {
            this["AutoReverse"] = 0;
        }
        if (!("AlternateNeutral" in $$source)) {
            this["AlternateNeutral"] = 0;
        }
        if (!("AIControl" in $$source)) {
            this["AIControl"] = 0;
        }
        if (!("CurrentPitSpeedLimit" in $$source)) {
            this["CurrentPitSpeedLimit"] = 0;
        }
        if (!("UnsubscribedBuffersMask" in $$source)) {
            this["UnsubscribedBuffersMask"] = 0;
        }
        if (!("SessionStarted" in $$source)) {
            this["SessionStarted"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Extended instance from a string or object.
     */
    static createFrom($$source: any = {}): Extended {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Extended($$parsedSource as Partial<Extended>);
    }
}

/**
 * ForceFeedback mirrors rF2ForceFeedback.
 */
export class ForceFeedback {
    "ForceValue": number;

    /** Creates a new ForceFeedback instance. */
    constructor($$source: Partial<ForceFeedback> = {}) {
        if (!("ForceValue" in $$source)) {
            this["ForceValue"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForceFeedback instance from a string or object.
     */
    static createFrom($$source: any = {}): ForceFeedback {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForceFeedback($$parsedSource as Partial<ForceFeedback>);
    }
}

/**
 * Frame is one consistent capture of all rF2 buffers: every car's full
 * telemetry (+ matched scoring) and the session globals. This is the decoded
 * payload reassembled from the chunked UDP datagrams.
 */
export class Frame {
    "Seq": number;
    "SMMPVersion": number;
    "PlayerID": number;
    "PlayerIdx": number;
    "ScoringInfo": ScoringInfo;
    "Weather": Weather;
    "Rules": Rules;
    "Extended": Extended;
    "Graphics": Graphics;
    "ForceFeedback": ForceFeedback;
    "PitMenu": PitMenu;
    "Vehicles": Vehicle[];

    /** Creates a new Frame instance. */
    constructor($$source: Partial<Frame> = {}) {
        if (!("Seq" in $$source)) {
            this["Seq"] = 0;
        }
        if (!("SMMPVersion" in $$source)) {
            this["SMMPVersion"] = 0;
        }
        if (!("PlayerID" in $$source)) {
            this["PlayerID"] = 0;
        }
        if (!("PlayerIdx" in $$source)) {
            this["PlayerIdx"] = 0;
        }
        if (!("ScoringInfo" in $$source)) {
            this["ScoringInfo"] = (new ScoringInfo());
        }
        if (!("Weather" in $$source)) {
            this["Weather"] = (new Weather());
        }
        if (!("Rules" in $$source)) {
            this["Rules"] = (new Rules());
        }
        if (!("Extended" in $$source)) {
            this["Extended"] = (new Extended());
        }
        if (!("Graphics" in $$source)) {
            this["Graphics"] = (new Graphics());
        }
        if (!("ForceFeedback" in $$source)) {
            this["ForceFeedback"] = (new ForceFeedback());
        }
        if (!("PitMenu" in $$source)) {
            this["PitMenu"] = (new PitMenu());
        }
        if (!("Vehicles" in $$source)) {
            this["Vehicles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Frame instance from a string or object.
     */
    static createFrom($$source: any = {}): Frame {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType5;
        const $$createField10_0 = $$createType6;
        const $$createField11_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ScoringInfo" in $$parsedSource) {
            $$parsedSource["ScoringInfo"] = $$createField4_0($$parsedSource["ScoringInfo"]);
        }
        if ("Weather" in $$parsedSource) {
            $$parsedSource["Weather"] = $$createField5_0($$parsedSource["Weather"]);
        }
        if ("Rules" in $$parsedSource) {
            $$parsedSource["Rules"] = $$createField6_0($$parsedSource["Rules"]);
        }
        if ("Extended" in $$parsedSource) {
            $$parsedSource["Extended"] = $$createField7_0($$parsedSource["Extended"]);
        }
        if ("Graphics" in $$parsedSource) {
            $$parsedSource["Graphics"] = $$createField8_0($$parsedSource["Graphics"]);
        }
        if ("ForceFeedback" in $$parsedSource) {
            $$parsedSource["ForceFeedback"] = $$createField9_0($$parsedSource["ForceFeedback"]);
        }
        if ("PitMenu" in $$parsedSource) {
            $$parsedSource["PitMenu"] = $$createField10_0($$parsedSource["PitMenu"]);
        }
        if ("Vehicles" in $$parsedSource) {
            $$parsedSource["Vehicles"] = $$createField11_0($$parsedSource["Vehicles"]);
        }
        return new Frame($$parsedSource as Partial<Frame>);
    }
}

/**
 * Graphics is a subset of rF2GraphicsInfo (camera state).
 */
export class Graphics {
    "CamPos": Vec3;

    /**
     * slot ID being viewed (-1 if invalid)
     */
    "ViewedID": number;
    "CameraType": number;

    /** Creates a new Graphics instance. */
    constructor($$source: Partial<Graphics> = {}) {
        if (!("CamPos" in $$source)) {
            this["CamPos"] = (new Vec3());
        }
        if (!("ViewedID" in $$source)) {
            this["ViewedID"] = 0;
        }
        if (!("CameraType" in $$source)) {
            this["CameraType"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Graphics instance from a string or object.
     */
    static createFrom($$source: any = {}): Graphics {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CamPos" in $$parsedSource) {
            $$parsedSource["CamPos"] = $$createField0_0($$parsedSource["CamPos"]);
        }
        return new Graphics($$parsedSource as Partial<Graphics>);
    }
}

/**
 * PitMenu is a subset of rF2PitMenu (the current pit selection).
 */
export class PitMenu {
    "CategoryIndex": number;
    "CategoryName": number[];
    "ChoiceIndex": number;
    "ChoiceString": number[];
    "NumChoices": number;

    /** Creates a new PitMenu instance. */
    constructor($$source: Partial<PitMenu> = {}) {
        if (!("CategoryIndex" in $$source)) {
            this["CategoryIndex"] = 0;
        }
        if (!("CategoryName" in $$source)) {
            this["CategoryName"] = Array.from({ length: 32 }, () => 0);
        }
        if (!("ChoiceIndex" in $$source)) {
            this["ChoiceIndex"] = 0;
        }
        if (!("ChoiceString" in $$source)) {
            this["ChoiceString"] = Array.from({ length: 32 }, () => 0);
        }
        if (!("NumChoices" in $$source)) {
            this["NumChoices"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PitMenu instance from a string or object.
     */
    static createFrom($$source: any = {}): PitMenu {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PitMenu($$parsedSource as Partial<PitMenu>);
    }
}

/**
 * Rules is the global track-rules state (subset of rF2TrackRules).
 */
export class Rules {
    "CurrentET": number;

    /**
     * rF2TrackRulesStage
     */
    "Stage": number;

    /**
     * rF2TrackRulesColumn
     */
    "PoleColumn": number;
    "YellowFlagDetected": number;
    "SafetyCarExists": number;
    "SafetyCarActive": number;
    "SafetyCarLaps": number;
    "SafetyCarThreshold": number;
    "YellowFlagState": number;
    "YellowFlagLaps": number;

    /**
     * 0=no change,1=go active,2=head for pits
     */
    "SafetyCarInstruction": number;
    "SafetyCarSpeed": number;

    /** Creates a new Rules instance. */
    constructor($$source: Partial<Rules> = {}) {
        if (!("CurrentET" in $$source)) {
            this["CurrentET"] = 0;
        }
        if (!("Stage" in $$source)) {
            this["Stage"] = 0;
        }
        if (!("PoleColumn" in $$source)) {
            this["PoleColumn"] = 0;
        }
        if (!("YellowFlagDetected" in $$source)) {
            this["YellowFlagDetected"] = 0;
        }
        if (!("SafetyCarExists" in $$source)) {
            this["SafetyCarExists"] = 0;
        }
        if (!("SafetyCarActive" in $$source)) {
            this["SafetyCarActive"] = 0;
        }
        if (!("SafetyCarLaps" in $$source)) {
            this["SafetyCarLaps"] = 0;
        }
        if (!("SafetyCarThreshold" in $$source)) {
            this["SafetyCarThreshold"] = 0;
        }
        if (!("YellowFlagState" in $$source)) {
            this["YellowFlagState"] = 0;
        }
        if (!("YellowFlagLaps" in $$source)) {
            this["YellowFlagLaps"] = 0;
        }
        if (!("SafetyCarInstruction" in $$source)) {
            this["SafetyCarInstruction"] = 0;
        }
        if (!("SafetyCarSpeed" in $$source)) {
            this["SafetyCarSpeed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rules instance from a string or object.
     */
    static createFrom($$source: any = {}): Rules {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rules($$parsedSource as Partial<Rules>);
    }
}

/**
 * ScoringInfo mirrors rF2ScoringInfo (ScoringInfoV01), sizeof == 548. It carries
 * the session globals and the base weather (the dedicated Weather buffer adds
 * finer detail). Note the embedded pointer fields are 8 bytes (64-bit plugin).
 */
export class ScoringInfo {
    "TrackName": number[];

    /**
     * 0=testday 1-4=practice 5-8=qual 9=warmup 10-13=race
     */
    "Session": number;
    "CurrentET": number;
    "EndET": number;
    "MaxLaps": number;
    "LapDist": number;
    "NumVehicles": number;
    "GamePhase": number;
    "YellowFlagState": number;
    "SectorFlag": number[];
    "StartLight": number;
    "NumRedLights": number;

    /**
     * bool
     */
    "InRealtime": number;
    "PlayerName": number[];
    "PlrFileName": number[];

    /**
     * weather
     * 0.0-1.0
     */
    "DarkCloud": number;

    /**
     * 0.0-1.0
     */
    "Raining": number;

    /**
     * Celsius
     */
    "AmbientTemp": number;

    /**
     * Celsius
     */
    "TrackTemp": number;
    "Wind": Vec3;
    "MinPathWetness": number;
    "MaxPathWetness": number;
    "GameMode": number;

    /**
     * bool
     */
    "IsPasswordProtected": number;
    "ServerPort": number;
    "ServerPublicIP": number;
    "MaxPlayers": number;
    "ServerName": number[];
    "StartET": number;
    "AvgPathWetness": number;

    /** Creates a new ScoringInfo instance. */
    constructor($$source: Partial<ScoringInfo> = {}) {
        if (!("TrackName" in $$source)) {
            this["TrackName"] = Array.from({ length: 64 }, () => 0);
        }
        if (!("Session" in $$source)) {
            this["Session"] = 0;
        }
        if (!("CurrentET" in $$source)) {
            this["CurrentET"] = 0;
        }
        if (!("EndET" in $$source)) {
            this["EndET"] = 0;
        }
        if (!("MaxLaps" in $$source)) {
            this["MaxLaps"] = 0;
        }
        if (!("LapDist" in $$source)) {
            this["LapDist"] = 0;
        }
        if (!("NumVehicles" in $$source)) {
            this["NumVehicles"] = 0;
        }
        if (!("GamePhase" in $$source)) {
            this["GamePhase"] = 0;
        }
        if (!("YellowFlagState" in $$source)) {
            this["YellowFlagState"] = 0;
        }
        if (!("SectorFlag" in $$source)) {
            this["SectorFlag"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("StartLight" in $$source)) {
            this["StartLight"] = 0;
        }
        if (!("NumRedLights" in $$source)) {
            this["NumRedLights"] = 0;
        }
        if (!("InRealtime" in $$source)) {
            this["InRealtime"] = 0;
        }
        if (!("PlayerName" in $$source)) {
            this["PlayerName"] = Array.from({ length: 32 }, () => 0);
        }
        if (!("PlrFileName" in $$source)) {
            this["PlrFileName"] = Array.from({ length: 64 }, () => 0);
        }
        if (!("DarkCloud" in $$source)) {
            this["DarkCloud"] = 0;
        }
        if (!("Raining" in $$source)) {
            this["Raining"] = 0;
        }
        if (!("AmbientTemp" in $$source)) {
            this["AmbientTemp"] = 0;
        }
        if (!("TrackTemp" in $$source)) {
            this["TrackTemp"] = 0;
        }
        if (!("Wind" in $$source)) {
            this["Wind"] = (new Vec3());
        }
        if (!("MinPathWetness" in $$source)) {
            this["MinPathWetness"] = 0;
        }
        if (!("MaxPathWetness" in $$source)) {
            this["MaxPathWetness"] = 0;
        }
        if (!("GameMode" in $$source)) {
            this["GameMode"] = 0;
        }
        if (!("IsPasswordProtected" in $$source)) {
            this["IsPasswordProtected"] = 0;
        }
        if (!("ServerPort" in $$source)) {
            this["ServerPort"] = 0;
        }
        if (!("ServerPublicIP" in $$source)) {
            this["ServerPublicIP"] = 0;
        }
        if (!("MaxPlayers" in $$source)) {
            this["MaxPlayers"] = 0;
        }
        if (!("ServerName" in $$source)) {
            this["ServerName"] = Array.from({ length: 32 }, () => 0);
        }
        if (!("StartET" in $$source)) {
            this["StartET"] = 0;
        }
        if (!("AvgPathWetness" in $$source)) {
            this["AvgPathWetness"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoringInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ScoringInfo {
        const $$createField19_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Wind" in $$parsedSource) {
            $$parsedSource["Wind"] = $$createField19_0($$parsedSource["Wind"]);
        }
        return new ScoringInfo($$parsedSource as Partial<ScoringInfo>);
    }
}

/**
 * Vec3 mirrors rF2Vec3 (three doubles, 24 bytes).
 */
export class Vec3 {
    "X": number;
    "Y": number;
    "Z": number;

    /** Creates a new Vec3 instance. */
    constructor($$source: Partial<Vec3> = {}) {
        if (!("X" in $$source)) {
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            this["Y"] = 0;
        }
        if (!("Z" in $$source)) {
            this["Z"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Vec3 instance from a string or object.
     */
    static createFrom($$source: any = {}): Vec3 {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Vec3($$parsedSource as Partial<Vec3>);
    }
}

/**
 * Vehicle is one car: its full telemetry plus, when matched, its scoring entry.
 * HasScoring is 0 when no scoring row matched this car's ID (the Scoring field
 * is then zero-valued).
 */
export class Vehicle {
    "Telemetry": VehicleTelemetry;
    "HasScoring": number;
    "Scoring": VehicleScoring;

    /** Creates a new Vehicle instance. */
    constructor($$source: Partial<Vehicle> = {}) {
        if (!("Telemetry" in $$source)) {
            this["Telemetry"] = (new VehicleTelemetry());
        }
        if (!("HasScoring" in $$source)) {
            this["HasScoring"] = 0;
        }
        if (!("Scoring" in $$source)) {
            this["Scoring"] = (new VehicleScoring());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Vehicle instance from a string or object.
     */
    static createFrom($$source: any = {}): Vehicle {
        const $$createField0_0 = $$createType10;
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Telemetry" in $$parsedSource) {
            $$parsedSource["Telemetry"] = $$createField0_0($$parsedSource["Telemetry"]);
        }
        if ("Scoring" in $$parsedSource) {
            $$parsedSource["Scoring"] = $$createField2_0($$parsedSource["Scoring"]);
        }
        return new Vehicle($$parsedSource as Partial<Vehicle>);
    }
}

/**
 * VehicleScoring mirrors rF2VehicleScoring (VehicleScoringInfoV01), sizeof == 584.
 */
export class VehicleScoring {
    "ID": number;
    "DriverName": number[];
    "VehicleName": number[];
    "TotalLaps": number;

    /**
     * 0=sector3,1=sector1,2=sector2
     */
    "Sector": number;

    /**
     * 0=none,1=finished,2=dnf,3=dq
     */
    "FinishStatus": number;
    "LapDist": number;
    "PathLateral": number;
    "TrackEdge": number;
    "BestSector1": number;
    "BestSector2": number;
    "BestLapTime": number;
    "LastSector1": number;
    "LastSector2": number;
    "LastLapTime": number;
    "CurSector1": number;
    "CurSector2": number;
    "NumPitstops": number;
    "NumPenalties": number;

    /**
     * bool
     */
    "IsPlayer": number;

    /**
     * who's in control: 0=local player,1=AI,2=remote (signed char, all values >=0 here)
     */
    "Control": number;

    /**
     * bool
     */
    "InPits": number;

    /**
     * 1-based position
     */
    "Place": number;
    "VehicleClass": number[];
    "TimeBehindNext": number;
    "LapsBehindNext": number;
    "TimeBehindLeader": number;
    "LapsBehindLeader": number;
    "LapStartET": number;
    "Pos": Vec3;
    "LocalVel": Vec3;
    "LocalAccel": Vec3;
    "Ori": Vec3[];
    "LocalRot": Vec3;
    "LocalRotAccel": Vec3;
    "Headlights": number;

    /**
     * 0=none,1=request,2=entering,3=stopped,4=exiting
     */
    "PitState": number;
    "ServerScored": number;
    "IndividualPhase": number;
    "Qualification": number;
    "TimeIntoLap": number;
    "EstimatedLapTime": number;
    "PitGroup": number[];

    /**
     * 0=green,6=blue
     */
    "Flag": number;

    /**
     * bool
     */
    "UnderYellow": number;
    "CountLapFlag": number;

    /**
     * bool
     */
    "InGarageStall": number;
    "UpgradePack": number[];
    "PitLapDist": number;
    "BestLapSector1": number;
    "BestLapSector2": number;

    /** Creates a new VehicleScoring instance. */
    constructor($$source: Partial<VehicleScoring> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("DriverName" in $$source)) {
            this["DriverName"] = Array.from({ length: 32 }, () => 0);
        }
        if (!("VehicleName" in $$source)) {
            this["VehicleName"] = Array.from({ length: 64 }, () => 0);
        }
        if (!("TotalLaps" in $$source)) {
            this["TotalLaps"] = 0;
        }
        if (!("Sector" in $$source)) {
            this["Sector"] = 0;
        }
        if (!("FinishStatus" in $$source)) {
            this["FinishStatus"] = 0;
        }
        if (!("LapDist" in $$source)) {
            this["LapDist"] = 0;
        }
        if (!("PathLateral" in $$source)) {
            this["PathLateral"] = 0;
        }
        if (!("TrackEdge" in $$source)) {
            this["TrackEdge"] = 0;
        }
        if (!("BestSector1" in $$source)) {
            this["BestSector1"] = 0;
        }
        if (!("BestSector2" in $$source)) {
            this["BestSector2"] = 0;
        }
        if (!("BestLapTime" in $$source)) {
            this["BestLapTime"] = 0;
        }
        if (!("LastSector1" in $$source)) {
            this["LastSector1"] = 0;
        }
        if (!("LastSector2" in $$source)) {
            this["LastSector2"] = 0;
        }
        if (!("LastLapTime" in $$source)) {
            this["LastLapTime"] = 0;
        }
        if (!("CurSector1" in $$source)) {
            this["CurSector1"] = 0;
        }
        if (!("CurSector2" in $$source)) {
            this["CurSector2"] = 0;
        }
        if (!("NumPitstops" in $$source)) {
            this["NumPitstops"] = 0;
        }
        if (!("NumPenalties" in $$source)) {
            this["NumPenalties"] = 0;
        }
        if (!("IsPlayer" in $$source)) {
            this["IsPlayer"] = 0;
        }
        if (!("Control" in $$source)) {
            this["Control"] = 0;
        }
        if (!("InPits" in $$source)) {
            this["InPits"] = 0;
        }
        if (!("Place" in $$source)) {
            this["Place"] = 0;
        }
        if (!("VehicleClass" in $$source)) {
            this["VehicleClass"] = Array.from({ length: 32 }, () => 0);
        }
        if (!("TimeBehindNext" in $$source)) {
            this["TimeBehindNext"] = 0;
        }
        if (!("LapsBehindNext" in $$source)) {
            this["LapsBehindNext"] = 0;
        }
        if (!("TimeBehindLeader" in $$source)) {
            this["TimeBehindLeader"] = 0;
        }
        if (!("LapsBehindLeader" in $$source)) {
            this["LapsBehindLeader"] = 0;
        }
        if (!("LapStartET" in $$source)) {
            this["LapStartET"] = 0;
        }
        if (!("Pos" in $$source)) {
            this["Pos"] = (new Vec3());
        }
        if (!("LocalVel" in $$source)) {
            this["LocalVel"] = (new Vec3());
        }
        if (!("LocalAccel" in $$source)) {
            this["LocalAccel"] = (new Vec3());
        }
        if (!("Ori" in $$source)) {
            this["Ori"] = Array.from({ length: 3 }, () => (new Vec3()));
        }
        if (!("LocalRot" in $$source)) {
            this["LocalRot"] = (new Vec3());
        }
        if (!("LocalRotAccel" in $$source)) {
            this["LocalRotAccel"] = (new Vec3());
        }
        if (!("Headlights" in $$source)) {
            this["Headlights"] = 0;
        }
        if (!("PitState" in $$source)) {
            this["PitState"] = 0;
        }
        if (!("ServerScored" in $$source)) {
            this["ServerScored"] = 0;
        }
        if (!("IndividualPhase" in $$source)) {
            this["IndividualPhase"] = 0;
        }
        if (!("Qualification" in $$source)) {
            this["Qualification"] = 0;
        }
        if (!("TimeIntoLap" in $$source)) {
            this["TimeIntoLap"] = 0;
        }
        if (!("EstimatedLapTime" in $$source)) {
            this["EstimatedLapTime"] = 0;
        }
        if (!("PitGroup" in $$source)) {
            this["PitGroup"] = Array.from({ length: 24 }, () => 0);
        }
        if (!("Flag" in $$source)) {
            this["Flag"] = 0;
        }
        if (!("UnderYellow" in $$source)) {
            this["UnderYellow"] = 0;
        }
        if (!("CountLapFlag" in $$source)) {
            this["CountLapFlag"] = 0;
        }
        if (!("InGarageStall" in $$source)) {
            this["InGarageStall"] = 0;
        }
        if (!("UpgradePack" in $$source)) {
            this["UpgradePack"] = Array.from({ length: 16 }, () => 0);
        }
        if (!("PitLapDist" in $$source)) {
            this["PitLapDist"] = 0;
        }
        if (!("BestLapSector1" in $$source)) {
            this["BestLapSector1"] = 0;
        }
        if (!("BestLapSector2" in $$source)) {
            this["BestLapSector2"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VehicleScoring instance from a string or object.
     */
    static createFrom($$source: any = {}): VehicleScoring {
        const $$createField29_0 = $$createType9;
        const $$createField30_0 = $$createType9;
        const $$createField31_0 = $$createType9;
        const $$createField32_0 = $$createType12;
        const $$createField33_0 = $$createType9;
        const $$createField34_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Pos" in $$parsedSource) {
            $$parsedSource["Pos"] = $$createField29_0($$parsedSource["Pos"]);
        }
        if ("LocalVel" in $$parsedSource) {
            $$parsedSource["LocalVel"] = $$createField30_0($$parsedSource["LocalVel"]);
        }
        if ("LocalAccel" in $$parsedSource) {
            $$parsedSource["LocalAccel"] = $$createField31_0($$parsedSource["LocalAccel"]);
        }
        if ("Ori" in $$parsedSource) {
            $$parsedSource["Ori"] = $$createField32_0($$parsedSource["Ori"]);
        }
        if ("LocalRot" in $$parsedSource) {
            $$parsedSource["LocalRot"] = $$createField33_0($$parsedSource["LocalRot"]);
        }
        if ("LocalRotAccel" in $$parsedSource) {
            $$parsedSource["LocalRotAccel"] = $$createField34_0($$parsedSource["LocalRotAccel"]);
        }
        return new VehicleScoring($$parsedSource as Partial<VehicleScoring>);
    }
}

/**
 * VehicleTelemetry mirrors rF2VehicleTelemetry (TelemInfoV01), sizeof == 1888.
 */
export class VehicleTelemetry {
    /**
     * slot ID (matches VehicleScoring.ID)
     */
    "ID": number;
    "DeltaTime": number;
    "ElapsedTime": number;
    "LapNumber": number;
    "LapStartET": number;
    "VehicleName": number[];
    "TrackName": number[];
    "Pos": Vec3;
    "LocalVel": Vec3;
    "LocalAccel": Vec3;

    /**
     * orientation matrix rows
     */
    "Ori": Vec3[];
    "LocalRot": Vec3;
    "LocalRotAccel": Vec3;

    /**
     * -1=reverse, 0=neutral, 1+=forward
     */
    "Gear": number;
    "EngineRPM": number;

    /**
     * Celsius
     */
    "EngineWaterTemp": number;

    /**
     * Celsius
     */
    "EngineOilTemp": number;
    "ClutchRPM": number;

    /**
     * 0..1
     */
    "UnfilteredThrottle": number;

    /**
     * 0..1
     */
    "UnfilteredBrake": number;

    /**
     * -1..1
     */
    "UnfilteredSteering": number;

    /**
     * 0..1
     */
    "UnfilteredClutch": number;
    "FilteredThrottle": number;
    "FilteredBrake": number;
    "FilteredSteering": number;
    "FilteredClutch": number;
    "SteeringShaftTorque": number;
    "Front3rdDeflection": number;
    "Rear3rdDeflection": number;
    "FrontWingHeight": number;
    "FrontRideHeight": number;
    "RearRideHeight": number;
    "Drag": number;
    "FrontDownforce": number;
    "RearDownforce": number;

    /**
     * liters
     */
    "Fuel": number;
    "EngineMaxRPM": number;
    "ScheduledStops": number;

    /**
     * bool
     */
    "Overheating": number;

    /**
     * bool
     */
    "Detached": number;

    /**
     * bool
     */
    "Headlights": number;
    "DentSeverity": number[];
    "LastImpactET": number;
    "LastImpactMagnitude": number;
    "LastImpactPos": Vec3;
    "EngineTorque": number;

    /**
     * pitlane stored in sign bit
     */
    "CurrentSector": number;
    "SpeedLimiter": number;
    "MaxGears": number;
    "FrontTireCompoundIndex": number;
    "RearTireCompoundIndex": number;
    "FuelCapacity": number;
    "FrontFlapActivated": number;
    "RearFlapActivated": number;
    "RearFlapLegalStatus": number;
    "IgnitionStarter": number;
    "FrontTireCompoundName": number[];
    "RearTireCompoundName": number[];
    "SpeedLimiterAvailable": number;
    "AntiStallActivated": number;
    "VisualSteeringWheelRange": number;
    "RearBrakeBias": number;
    "TurboBoostPressure": number;
    "PhysicsToGraphicsOffset": number[];

    /**
     * lock-to-lock degrees
     */
    "PhysicalSteeringWheelRange": number;

    /**
     * 0.0-1.0
     */
    "BatteryChargeFraction": number;
    "ElectricBoostMotorTorque": number;
    "ElectricBoostMotorRPM": number;
    "ElectricBoostMotorTemperature": number;
    "ElectricBoostWaterTemperature": number;

    /**
     * 0=unavail,1=inactive,2=propulsion,3=regen
     */
    "ElectricBoostMotorState": number;

    /**
     * front-left, front-right, rear-left, rear-right
     */
    "Wheels": Wheel[];

    /** Creates a new VehicleTelemetry instance. */
    constructor($$source: Partial<VehicleTelemetry> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("DeltaTime" in $$source)) {
            this["DeltaTime"] = 0;
        }
        if (!("ElapsedTime" in $$source)) {
            this["ElapsedTime"] = 0;
        }
        if (!("LapNumber" in $$source)) {
            this["LapNumber"] = 0;
        }
        if (!("LapStartET" in $$source)) {
            this["LapStartET"] = 0;
        }
        if (!("VehicleName" in $$source)) {
            this["VehicleName"] = Array.from({ length: 64 }, () => 0);
        }
        if (!("TrackName" in $$source)) {
            this["TrackName"] = Array.from({ length: 64 }, () => 0);
        }
        if (!("Pos" in $$source)) {
            this["Pos"] = (new Vec3());
        }
        if (!("LocalVel" in $$source)) {
            this["LocalVel"] = (new Vec3());
        }
        if (!("LocalAccel" in $$source)) {
            this["LocalAccel"] = (new Vec3());
        }
        if (!("Ori" in $$source)) {
            this["Ori"] = Array.from({ length: 3 }, () => (new Vec3()));
        }
        if (!("LocalRot" in $$source)) {
            this["LocalRot"] = (new Vec3());
        }
        if (!("LocalRotAccel" in $$source)) {
            this["LocalRotAccel"] = (new Vec3());
        }
        if (!("Gear" in $$source)) {
            this["Gear"] = 0;
        }
        if (!("EngineRPM" in $$source)) {
            this["EngineRPM"] = 0;
        }
        if (!("EngineWaterTemp" in $$source)) {
            this["EngineWaterTemp"] = 0;
        }
        if (!("EngineOilTemp" in $$source)) {
            this["EngineOilTemp"] = 0;
        }
        if (!("ClutchRPM" in $$source)) {
            this["ClutchRPM"] = 0;
        }
        if (!("UnfilteredThrottle" in $$source)) {
            this["UnfilteredThrottle"] = 0;
        }
        if (!("UnfilteredBrake" in $$source)) {
            this["UnfilteredBrake"] = 0;
        }
        if (!("UnfilteredSteering" in $$source)) {
            this["UnfilteredSteering"] = 0;
        }
        if (!("UnfilteredClutch" in $$source)) {
            this["UnfilteredClutch"] = 0;
        }
        if (!("FilteredThrottle" in $$source)) {
            this["FilteredThrottle"] = 0;
        }
        if (!("FilteredBrake" in $$source)) {
            this["FilteredBrake"] = 0;
        }
        if (!("FilteredSteering" in $$source)) {
            this["FilteredSteering"] = 0;
        }
        if (!("FilteredClutch" in $$source)) {
            this["FilteredClutch"] = 0;
        }
        if (!("SteeringShaftTorque" in $$source)) {
            this["SteeringShaftTorque"] = 0;
        }
        if (!("Front3rdDeflection" in $$source)) {
            this["Front3rdDeflection"] = 0;
        }
        if (!("Rear3rdDeflection" in $$source)) {
            this["Rear3rdDeflection"] = 0;
        }
        if (!("FrontWingHeight" in $$source)) {
            this["FrontWingHeight"] = 0;
        }
        if (!("FrontRideHeight" in $$source)) {
            this["FrontRideHeight"] = 0;
        }
        if (!("RearRideHeight" in $$source)) {
            this["RearRideHeight"] = 0;
        }
        if (!("Drag" in $$source)) {
            this["Drag"] = 0;
        }
        if (!("FrontDownforce" in $$source)) {
            this["FrontDownforce"] = 0;
        }
        if (!("RearDownforce" in $$source)) {
            this["RearDownforce"] = 0;
        }
        if (!("Fuel" in $$source)) {
            this["Fuel"] = 0;
        }
        if (!("EngineMaxRPM" in $$source)) {
            this["EngineMaxRPM"] = 0;
        }
        if (!("ScheduledStops" in $$source)) {
            this["ScheduledStops"] = 0;
        }
        if (!("Overheating" in $$source)) {
            this["Overheating"] = 0;
        }
        if (!("Detached" in $$source)) {
            this["Detached"] = 0;
        }
        if (!("Headlights" in $$source)) {
            this["Headlights"] = 0;
        }
        if (!("DentSeverity" in $$source)) {
            this["DentSeverity"] = Array.from({ length: 8 }, () => 0);
        }
        if (!("LastImpactET" in $$source)) {
            this["LastImpactET"] = 0;
        }
        if (!("LastImpactMagnitude" in $$source)) {
            this["LastImpactMagnitude"] = 0;
        }
        if (!("LastImpactPos" in $$source)) {
            this["LastImpactPos"] = (new Vec3());
        }
        if (!("EngineTorque" in $$source)) {
            this["EngineTorque"] = 0;
        }
        if (!("CurrentSector" in $$source)) {
            this["CurrentSector"] = 0;
        }
        if (!("SpeedLimiter" in $$source)) {
            this["SpeedLimiter"] = 0;
        }
        if (!("MaxGears" in $$source)) {
            this["MaxGears"] = 0;
        }
        if (!("FrontTireCompoundIndex" in $$source)) {
            this["FrontTireCompoundIndex"] = 0;
        }
        if (!("RearTireCompoundIndex" in $$source)) {
            this["RearTireCompoundIndex"] = 0;
        }
        if (!("FuelCapacity" in $$source)) {
            this["FuelCapacity"] = 0;
        }
        if (!("FrontFlapActivated" in $$source)) {
            this["FrontFlapActivated"] = 0;
        }
        if (!("RearFlapActivated" in $$source)) {
            this["RearFlapActivated"] = 0;
        }
        if (!("RearFlapLegalStatus" in $$source)) {
            this["RearFlapLegalStatus"] = 0;
        }
        if (!("IgnitionStarter" in $$source)) {
            this["IgnitionStarter"] = 0;
        }
        if (!("FrontTireCompoundName" in $$source)) {
            this["FrontTireCompoundName"] = Array.from({ length: 18 }, () => 0);
        }
        if (!("RearTireCompoundName" in $$source)) {
            this["RearTireCompoundName"] = Array.from({ length: 18 }, () => 0);
        }
        if (!("SpeedLimiterAvailable" in $$source)) {
            this["SpeedLimiterAvailable"] = 0;
        }
        if (!("AntiStallActivated" in $$source)) {
            this["AntiStallActivated"] = 0;
        }
        if (!("VisualSteeringWheelRange" in $$source)) {
            this["VisualSteeringWheelRange"] = 0;
        }
        if (!("RearBrakeBias" in $$source)) {
            this["RearBrakeBias"] = 0;
        }
        if (!("TurboBoostPressure" in $$source)) {
            this["TurboBoostPressure"] = 0;
        }
        if (!("PhysicsToGraphicsOffset" in $$source)) {
            this["PhysicsToGraphicsOffset"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("PhysicalSteeringWheelRange" in $$source)) {
            this["PhysicalSteeringWheelRange"] = 0;
        }
        if (!("BatteryChargeFraction" in $$source)) {
            this["BatteryChargeFraction"] = 0;
        }
        if (!("ElectricBoostMotorTorque" in $$source)) {
            this["ElectricBoostMotorTorque"] = 0;
        }
        if (!("ElectricBoostMotorRPM" in $$source)) {
            this["ElectricBoostMotorRPM"] = 0;
        }
        if (!("ElectricBoostMotorTemperature" in $$source)) {
            this["ElectricBoostMotorTemperature"] = 0;
        }
        if (!("ElectricBoostWaterTemperature" in $$source)) {
            this["ElectricBoostWaterTemperature"] = 0;
        }
        if (!("ElectricBoostMotorState" in $$source)) {
            this["ElectricBoostMotorState"] = 0;
        }
        if (!("Wheels" in $$source)) {
            this["Wheels"] = Array.from({ length: 4 }, () => (new Wheel()));
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VehicleTelemetry instance from a string or object.
     */
    static createFrom($$source: any = {}): VehicleTelemetry {
        const $$createField7_0 = $$createType9;
        const $$createField8_0 = $$createType9;
        const $$createField9_0 = $$createType9;
        const $$createField10_0 = $$createType12;
        const $$createField11_0 = $$createType9;
        const $$createField12_0 = $$createType9;
        const $$createField44_0 = $$createType9;
        const $$createField71_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Pos" in $$parsedSource) {
            $$parsedSource["Pos"] = $$createField7_0($$parsedSource["Pos"]);
        }
        if ("LocalVel" in $$parsedSource) {
            $$parsedSource["LocalVel"] = $$createField8_0($$parsedSource["LocalVel"]);
        }
        if ("LocalAccel" in $$parsedSource) {
            $$parsedSource["LocalAccel"] = $$createField9_0($$parsedSource["LocalAccel"]);
        }
        if ("Ori" in $$parsedSource) {
            $$parsedSource["Ori"] = $$createField10_0($$parsedSource["Ori"]);
        }
        if ("LocalRot" in $$parsedSource) {
            $$parsedSource["LocalRot"] = $$createField11_0($$parsedSource["LocalRot"]);
        }
        if ("LocalRotAccel" in $$parsedSource) {
            $$parsedSource["LocalRotAccel"] = $$createField12_0($$parsedSource["LocalRotAccel"]);
        }
        if ("LastImpactPos" in $$parsedSource) {
            $$parsedSource["LastImpactPos"] = $$createField44_0($$parsedSource["LastImpactPos"]);
        }
        if ("Wheels" in $$parsedSource) {
            $$parsedSource["Wheels"] = $$createField71_0($$parsedSource["Wheels"]);
        }
        return new VehicleTelemetry($$parsedSource as Partial<VehicleTelemetry>);
    }
}

/**
 * Weather is the detailed weather from the dedicated Weather buffer
 * (rF2Weather + rF2WeatherControlInfo). Base weather (rain/temps/wind) is also
 * in ScoringInfo; this adds cloudiness, the 3x3 rain grid and the control ET.
 */
export class Weather {
    "TrackNodeSize": number;

    /**
     * when the weather takes effect
     */
    "ET": number;

    /**
     * 3x3 rain grid (0.0-1.0)
     */
    "Raining": number[];

    /**
     * 0.0-1.0
     */
    "Cloudiness": number;

    /**
     * Kelvin
     */
    "AmbientTempK": number;
    "WindMaxSpeed": number;

    /** Creates a new Weather instance. */
    constructor($$source: Partial<Weather> = {}) {
        if (!("TrackNodeSize" in $$source)) {
            this["TrackNodeSize"] = 0;
        }
        if (!("ET" in $$source)) {
            this["ET"] = 0;
        }
        if (!("Raining" in $$source)) {
            this["Raining"] = Array.from({ length: 9 }, () => 0);
        }
        if (!("Cloudiness" in $$source)) {
            this["Cloudiness"] = 0;
        }
        if (!("AmbientTempK" in $$source)) {
            this["AmbientTempK"] = 0;
        }
        if (!("WindMaxSpeed" in $$source)) {
            this["WindMaxSpeed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Weather instance from a string or object.
     */
    static createFrom($$source: any = {}): Weather {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Weather($$parsedSource as Partial<Weather>);
    }
}

/**
 * Wheel mirrors rF2Wheel (TelemWheelV01), sizeof == 260 under pack(4).
 */
export class Wheel {
    /**
     * meters
     */
    "SuspensionDeflection": number;

    /**
     * meters
     */
    "RideHeight": number;

    /**
     * pushrod load, Newtons
     */
    "SuspForce": number;

    /**
     * Celsius
     */
    "BrakeTemp": number;

    /**
     * 0.0-1.0
     */
    "BrakePressure": number;

    /**
     * radians/sec
     */
    "Rotation": number;
    "LateralPatchVel": number;
    "LongitudinalPatchVel": number;
    "LateralGroundVel": number;
    "LongitudinalGroundVel": number;

    /**
     * radians
     */
    "Camber": number;

    /**
     * Newtons
     */
    "LateralForce": number;

    /**
     * Newtons
     */
    "LongitudinalForce": number;

    /**
     * Newtons
     */
    "TireLoad": number;

    /**
     * fraction of contact patch sliding
     */
    "GripFract": number;

    /**
     * kPa
     */
    "Pressure": number;

    /**
     * Kelvin, left/center/right
     */
    "Temperature": number[];

    /**
     * 0.0-1.0
     */
    "Wear": number;

    /**
     * TDF material prefix
     */
    "TerrainName": number[];

    /**
     * 0=dry,1=wet,2=grass,3=dirt,4=gravel,5=kerb,6=special
     */
    "SurfaceType": number;

    /**
     * bool: tire flat
     */
    "Flat": number;

    /**
     * bool: wheel detached
     */
    "Detached": number;

    /**
     * centimeters
     */
    "StaticUndeflectedRadius": number;
    "VerticalTireDeflection": number;
    "WheelYLocation": number;
    "Toe": number;

    /**
     * Kelvin
     */
    "TireCarcassTemperature": number;

    /**
     * Kelvin
     */
    "TireInnerLayerTemperature": number[];

    /** Creates a new Wheel instance. */
    constructor($$source: Partial<Wheel> = {}) {
        if (!("SuspensionDeflection" in $$source)) {
            this["SuspensionDeflection"] = 0;
        }
        if (!("RideHeight" in $$source)) {
            this["RideHeight"] = 0;
        }
        if (!("SuspForce" in $$source)) {
            this["SuspForce"] = 0;
        }
        if (!("BrakeTemp" in $$source)) {
            this["BrakeTemp"] = 0;
        }
        if (!("BrakePressure" in $$source)) {
            this["BrakePressure"] = 0;
        }
        if (!("Rotation" in $$source)) {
            this["Rotation"] = 0;
        }
        if (!("LateralPatchVel" in $$source)) {
            this["LateralPatchVel"] = 0;
        }
        if (!("LongitudinalPatchVel" in $$source)) {
            this["LongitudinalPatchVel"] = 0;
        }
        if (!("LateralGroundVel" in $$source)) {
            this["LateralGroundVel"] = 0;
        }
        if (!("LongitudinalGroundVel" in $$source)) {
            this["LongitudinalGroundVel"] = 0;
        }
        if (!("Camber" in $$source)) {
            this["Camber"] = 0;
        }
        if (!("LateralForce" in $$source)) {
            this["LateralForce"] = 0;
        }
        if (!("LongitudinalForce" in $$source)) {
            this["LongitudinalForce"] = 0;
        }
        if (!("TireLoad" in $$source)) {
            this["TireLoad"] = 0;
        }
        if (!("GripFract" in $$source)) {
            this["GripFract"] = 0;
        }
        if (!("Pressure" in $$source)) {
            this["Pressure"] = 0;
        }
        if (!("Temperature" in $$source)) {
            this["Temperature"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("Wear" in $$source)) {
            this["Wear"] = 0;
        }
        if (!("TerrainName" in $$source)) {
            this["TerrainName"] = Array.from({ length: 16 }, () => 0);
        }
        if (!("SurfaceType" in $$source)) {
            this["SurfaceType"] = 0;
        }
        if (!("Flat" in $$source)) {
            this["Flat"] = 0;
        }
        if (!("Detached" in $$source)) {
            this["Detached"] = 0;
        }
        if (!("StaticUndeflectedRadius" in $$source)) {
            this["StaticUndeflectedRadius"] = 0;
        }
        if (!("VerticalTireDeflection" in $$source)) {
            this["VerticalTireDeflection"] = 0;
        }
        if (!("WheelYLocation" in $$source)) {
            this["WheelYLocation"] = 0;
        }
        if (!("Toe" in $$source)) {
            this["Toe"] = 0;
        }
        if (!("TireCarcassTemperature" in $$source)) {
            this["TireCarcassTemperature"] = 0;
        }
        if (!("TireInnerLayerTemperature" in $$source)) {
            this["TireInnerLayerTemperature"] = Array.from({ length: 3 }, () => 0);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Wheel instance from a string or object.
     */
    static createFrom($$source: any = {}): Wheel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Wheel($$parsedSource as Partial<Wheel>);
    }
}

// Private type creation functions
const $$createType0 = ScoringInfo.createFrom;
const $$createType1 = Weather.createFrom;
const $$createType2 = Rules.createFrom;
const $$createType3 = Extended.createFrom;
const $$createType4 = Graphics.createFrom;
const $$createType5 = ForceFeedback.createFrom;
const $$createType6 = PitMenu.createFrom;
const $$createType7 = Vehicle.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = Vec3.createFrom;
const $$createType10 = VehicleTelemetry.createFrom;
const $$createType11 = VehicleScoring.createFrom;
const $$createType12 = $Create.Array($$createType9);
const $$createType13 = Wheel.createFrom;
const $$createType14 = $Create.Array($$createType13);
