// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Device describes a connected MOZA USB device discovered by Detect. Port is the
 * serial device path the driver opens (e.g. /dev/ttyACM1 on Linux); Model is the
 * USB product string the device reports ("MOZA R12 Base"); Serial is the unique
 * per-unit serial number. ProductID is the USB product ID, used to look up a
 * lighting Profile (see profile.go).
 */
export class Device {
    "port": string;
    "model": string;
    "serial": string;
    "product_id": number;

    /**
     * Wheel is the attached rim's model code (e.g. "ES", "KS"), read over serial
     * via DetectWheel. Empty when no rim answered or detection did not run. The
     * base USB descriptor (Model) identifies the base, not the rim.
     */
    "wheel": string;

    /** Creates a new Device instance. */
    constructor($$source: Partial<Device> = {}) {
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("product_id" in $$source)) {
            this["product_id"] = 0;
        }
        if (!("wheel" in $$source)) {
            this["wheel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     */
    static createFrom($$source: any = {}): Device {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Device($$parsedSource as Partial<Device>);
    }
}
