// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as forza$0 from "../forza/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * OverlayStatus reports whether the native overlay is currently running.
 */
export class OverlayStatus {
    "running": boolean;

    /** Creates a new OverlayStatus instance. */
    constructor($$source: Partial<OverlayStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverlayStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): OverlayStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverlayStatus($$parsedSource as Partial<OverlayStatus>);
    }
}

/**
 * ReplaySample is a single telemetry frame from a recording, offset from the
 * start of the recording in milliseconds.
 */
export class ReplaySample {
    "offset_ms": number;
    "telemetry": forza$0.Telemetry;

    /** Creates a new ReplaySample instance. */
    constructor($$source: Partial<ReplaySample> = {}) {
        if (!("offset_ms" in $$source)) {
            this["offset_ms"] = 0;
        }
        if (!("telemetry" in $$source)) {
            this["telemetry"] = (new forza$0.Telemetry());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplaySample instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplaySample {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("telemetry" in $$parsedSource) {
            $$parsedSource["telemetry"] = $$createField1_0($$parsedSource["telemetry"]);
        }
        return new ReplaySample($$parsedSource as Partial<ReplaySample>);
    }
}

/**
 * TelemetrySnapshot is the latest parsed telemetry frame plus metadata about
 * when it was received. It is returned to the frontend over the Wails bindings.
 */
export class TelemetrySnapshot {
    "telemetry": forza$0.Telemetry;
    "received_at": time$0.Time;
    "available": boolean;

    /** Creates a new TelemetrySnapshot instance. */
    constructor($$source: Partial<TelemetrySnapshot> = {}) {
        if (!("telemetry" in $$source)) {
            this["telemetry"] = (new forza$0.Telemetry());
        }
        if (!("received_at" in $$source)) {
            this["received_at"] = null;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TelemetrySnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): TelemetrySnapshot {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("telemetry" in $$parsedSource) {
            $$parsedSource["telemetry"] = $$createField0_0($$parsedSource["telemetry"]);
        }
        return new TelemetrySnapshot($$parsedSource as Partial<TelemetrySnapshot>);
    }
}

// Private type creation functions
const $$createType0 = forza$0.Telemetry.createFrom;
