// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as forza$0 from "../forza/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * ConfigStatus reports whether the config file failed to load at startup. When
 * Error is non-empty the app is running on default settings and the dashboard
 * shows a warning banner.
 */
export class ConfigStatus {
    "path": string;
    "error": string;

    /** Creates a new ConfigStatus instance. */
    constructor($$source: Partial<ConfigStatus> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigStatus($$parsedSource as Partial<ConfigStatus>);
    }
}

/**
 * MonitorInfo reports the logical resolution of the monitor the overlay will
 * appear on, so the dashboard can render an accurate placement preview. When
 * Detected is false the resolution was not auto-detectable (e.g. not running
 * under Hyprland) and the UI should let the user pick a resolution manually.
 */
export class MonitorInfo {
    "width": number;
    "height": number;
    "name": string;
    "detected": boolean;

    /** Creates a new MonitorInfo instance. */
    constructor($$source: Partial<MonitorInfo> = {}) {
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("detected" in $$source)) {
            this["detected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorInfo($$parsedSource as Partial<MonitorInfo>);
    }
}

/**
 * OverlayStatus reports the overlay's desired (user toggle) and actual
 * (native window) state. Enabled without Running means the overlay is on but
 * waiting for the game to start sending telemetry.
 */
export class OverlayStatus {
    "enabled": boolean;
    "running": boolean;

    /** Creates a new OverlayStatus instance. */
    constructor($$source: Partial<OverlayStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverlayStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): OverlayStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverlayStatus($$parsedSource as Partial<OverlayStatus>);
    }
}

/**
 * ReplaySample is a single telemetry frame from a recording, offset from the
 * start of the recording in milliseconds. Source/Meta mirror the live
 * TelemetrySnapshot so the dashboard can tailor a replay/review per game.
 */
export class ReplaySample {
    "offset_ms": number;
    "telemetry": forza$0.Telemetry;
    "source": string;
    "meta": TelemetryMeta;

    /** Creates a new ReplaySample instance. */
    constructor($$source: Partial<ReplaySample> = {}) {
        if (!("offset_ms" in $$source)) {
            this["offset_ms"] = 0;
        }
        if (!("telemetry" in $$source)) {
            this["telemetry"] = (new forza$0.Telemetry());
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new TelemetryMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplaySample instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplaySample {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("telemetry" in $$parsedSource) {
            $$parsedSource["telemetry"] = $$createField1_0($$parsedSource["telemetry"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField3_0($$parsedSource["meta"]);
        }
        return new ReplaySample($$parsedSource as Partial<ReplaySample>);
    }
}

/**
 * TelemetryMeta carries descriptive session info that does not fit the binary
 * forza.Telemetry model (which has no string fields). It is populated per source
 * — currently LMU, which sends the car/track names the dashboard's Info tab
 * shows. Forza leaves it zero-valued.
 */
export class TelemetryMeta {
    /**
     * vehicle/car name
     */
    "car": string;

    /**
     * track name
     */
    "track": string;

    /**
     * elapsed session time (seconds)
     */
    "session_time": number;

    /**
     * cars in the session
     */
    "num_vehicles": number;

    /**
     * SteeringRangeDeg is the car's lock-to-lock steering rotation in degrees
     * (LMU reports it per car). 0 when the game doesn't provide it (Forza), in
     * which case the overlay falls back to the configured default.
     */
    "steering_range_deg": number;

    /** Creates a new TelemetryMeta instance. */
    constructor($$source: Partial<TelemetryMeta> = {}) {
        if (!("car" in $$source)) {
            this["car"] = "";
        }
        if (!("track" in $$source)) {
            this["track"] = "";
        }
        if (!("session_time" in $$source)) {
            this["session_time"] = 0;
        }
        if (!("num_vehicles" in $$source)) {
            this["num_vehicles"] = 0;
        }
        if (!("steering_range_deg" in $$source)) {
            this["steering_range_deg"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TelemetryMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): TelemetryMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TelemetryMeta($$parsedSource as Partial<TelemetryMeta>);
    }
}

/**
 * TelemetrySnapshot is the latest parsed telemetry frame plus metadata about
 * when it was received. It is returned to the frontend over the Wails bindings.
 */
export class TelemetrySnapshot {
    "telemetry": forza$0.Telemetry;
    "received_at": time$0.Time;
    "available": boolean;

    /**
     * Source identifies the game that produced the latest frame ("forza" or
     * "lmu"), so the dashboard can tailor which tabs/readouts it shows. Empty
     * until the first packet arrives.
     */
    "source": string;

    /**
     * Meta is descriptive session info (car/track names, etc.) that has no place
     * in the binary telemetry struct. Surfaced on the dashboard's Info tab.
     */
    "meta": TelemetryMeta;

    /** Creates a new TelemetrySnapshot instance. */
    constructor($$source: Partial<TelemetrySnapshot> = {}) {
        if (!("telemetry" in $$source)) {
            this["telemetry"] = (new forza$0.Telemetry());
        }
        if (!("received_at" in $$source)) {
            this["received_at"] = null;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new TelemetryMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TelemetrySnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): TelemetrySnapshot {
        const $$createField0_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("telemetry" in $$parsedSource) {
            $$parsedSource["telemetry"] = $$createField0_0($$parsedSource["telemetry"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField4_0($$parsedSource["meta"]);
        }
        return new TelemetrySnapshot($$parsedSource as Partial<TelemetrySnapshot>);
    }
}

// Private type creation functions
const $$createType0 = forza$0.Telemetry.createFrom;
const $$createType1 = TelemetryMeta.createFrom;
