// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as forza$0 from "../game/forza/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * ConfigStatus reports whether the config file failed to load at startup. When
 * Error is non-empty the app is running on default settings and the dashboard
 * shows a warning banner.
 */
export class ConfigStatus {
    "path": string;
    "error": string;

    /** Creates a new ConfigStatus instance. */
    constructor($$source: Partial<ConfigStatus> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigStatus($$parsedSource as Partial<ConfigStatus>);
    }
}

/**
 * MonitorInfo reports the logical resolution of the monitor the overlay will
 * appear on, so the dashboard can render an accurate placement preview. When
 * Detected is false the resolution was not auto-detectable (e.g. not running
 * under Hyprland) and the UI should let the user pick a resolution manually.
 */
export class MonitorInfo {
    "width": number;
    "height": number;
    "name": string;
    "detected": boolean;

    /** Creates a new MonitorInfo instance. */
    constructor($$source: Partial<MonitorInfo> = {}) {
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("detected" in $$source)) {
            this["detected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorInfo($$parsedSource as Partial<MonitorInfo>);
    }
}

/**
 * MozaApplyResult is what came of a settings write, verified by reading the
 * values back rather than by trusting the base's acknowledgements.
 * 
 * A partial apply is a real outcome, not an exception: an older base may not
 * implement one command in a patch, and the user has to be able to tell which of
 * their changes are live and which are not.
 */
export class MozaApplyResult {
    /**
     * Ok is true only when every requested setting was written AND read back as
     * written.
     */
    "ok": boolean;

    /**
     * Refused is set when nothing was attempted — writes disabled, no wheelbase,
     * an unknown key, a value out of range. Nothing reached the hardware.
     */
    "refused": string;

    /**
     * Applied lists the settings written, in the order they were written.
     */
    "applied": string[];

    /**
     * Failed maps a setting to why its write failed. Strings rather than errors
     * because this crosses the bindings.
     */
    "failed": { [_ in string]?: string };

    /**
     * Mismatched names settings the base acknowledged but did not actually take.
     * This is what a dropped write looks like from the outside, and it is the
     * reason the result is read back at all.
     */
    "mismatched": { [_ in string]?: number };

    /**
     * Settings is a fresh read of everything after the write, so the page shows
     * the wheel's real state rather than what it hoped for.
     */
    "settings": { [_ in string]?: number };

    /**
     * Rewritten maps a setting to the one in the same patch that overwrites it as
     * a side effect. Applying still works — the ordering makes the explicit value
     * win — but the user asked for two things that interact and should be told.
     */
    "rewritten": { [_ in string]?: string };

    /** Creates a new MozaApplyResult instance. */
    constructor($$source: Partial<MozaApplyResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("refused" in $$source)) {
            this["refused"] = "";
        }
        if (!("applied" in $$source)) {
            this["applied"] = [];
        }
        if (!("failed" in $$source)) {
            this["failed"] = {};
        }
        if (!("mismatched" in $$source)) {
            this["mismatched"] = {};
        }
        if (!("settings" in $$source)) {
            this["settings"] = {};
        }
        if (!("rewritten" in $$source)) {
            this["rewritten"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MozaApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MozaApplyResult {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("applied" in $$parsedSource) {
            $$parsedSource["applied"] = $$createField2_0($$parsedSource["applied"]);
        }
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField3_0($$parsedSource["failed"]);
        }
        if ("mismatched" in $$parsedSource) {
            $$parsedSource["mismatched"] = $$createField4_0($$parsedSource["mismatched"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField5_0($$parsedSource["settings"]);
        }
        if ("rewritten" in $$parsedSource) {
            $$parsedSource["rewritten"] = $$createField6_0($$parsedSource["rewritten"]);
        }
        return new MozaApplyResult($$parsedSource as Partial<MozaApplyResult>);
    }
}

/**
 * MozaBaseCommand is one wheelbase setting's metadata, as the frontend needs it.
 * It mirrors moza.BaseCommand rather than exposing it directly, so the wire type
 * stays stable if the internal one gains fields.
 */
export class MozaBaseCommand {
    "key": string;
    "name": string;
    "unit": string;
    "min": number;
    "max": number;
    "kind": string;
    "labels": string[];

    /**
     * Safety marks the settings written first by a grouped apply, so the UI can
     * group them together as the safety envelope.
     */
    "safety": boolean;

    /**
     * Verified is false while a command's range and scaling are still taken from
     * Boxflat's database rather than confirmed on this hardware. The UI should
     * say so rather than presenting a guess as fact.
     */
    "verified": boolean;
    "note": string;

    /**
     * Affects names settings this one rewrites as a side effect — road sensitivity
     * is a macro on this firmware and moves the equalizer bands with it. The UI
     * needs this before the apply, not after, so it can say that changing one
     * control will move others the user can see on the same page.
     */
    "affects": string[];

    /** Creates a new MozaBaseCommand instance. */
    constructor($$source: Partial<MozaBaseCommand> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("min" in $$source)) {
            this["min"] = 0;
        }
        if (!("max" in $$source)) {
            this["max"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }
        if (!("safety" in $$source)) {
            this["safety"] = false;
        }
        if (!("verified" in $$source)) {
            this["verified"] = false;
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }
        if (!("affects" in $$source)) {
            this["affects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MozaBaseCommand instance from a string or object.
     */
    static createFrom($$source: any = {}): MozaBaseCommand {
        const $$createField6_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField6_0($$parsedSource["labels"]);
        }
        if ("affects" in $$parsedSource) {
            $$parsedSource["affects"] = $$createField10_0($$parsedSource["affects"]);
        }
        return new MozaBaseCommand($$parsedSource as Partial<MozaBaseCommand>);
    }
}

/**
 * MozaBaseSnapshot is the read-only view of the wheelbase's stored configuration
 * that the dashboard renders: what the device currently holds, what it declined
 * to answer, and its temperatures.
 * 
 * Values are keyed by the command keys in moza.BaseCommands(), which is also
 * where their ranges, units and labels live — so the frontend builds its controls
 * from the same source that validates the writes, and cannot offer a value the
 * hardware would reject.
 */
export class MozaBaseSnapshot {
    /**
     * Available is false when there is no wheelbase to talk to. The rest of the
     * struct is then empty and Reason says why, so the page can explain itself
     * rather than showing a grid of zeroes.
     */
    "available": boolean;
    "reason": string;
    "settings": { [_ in string]?: number };

    /**
     * Temps are degrees Celsius. The base reports hundredths of a degree; the
     * conversion happens in moza so every consumer sees the same units.
     */
    "temps": { [_ in string]?: number };

    /**
     * State and Error are the base's raw state words, shown when the base
     * answered them. Their values are not decoded yet, but a non-zero error is
     * worth surfacing before we can name it.
     */
    "state": number;
    "error": number;
    "has_state": boolean;
    "has_error": boolean;

    /**
     * Unsupported names commands this base did not answer. They are shown as
     * unavailable rather than as a value, because an older base legitimately
     * implements only part of the command set.
     */
    "unsupported": { [_ in string]?: boolean };

    /**
     * Writable reports whether the app is allowed to change these settings at all
     * (config `moza.allow_base_writes`). When false, WriteBlocked says why, and
     * the page renders as it did before writing existed — controls disabled with
     * a reason rather than hidden.
     */
    "writable": boolean;
    "write_blocked": string;

    /** Creates a new MozaBaseSnapshot instance. */
    constructor($$source: Partial<MozaBaseSnapshot> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("settings" in $$source)) {
            this["settings"] = {};
        }
        if (!("temps" in $$source)) {
            this["temps"] = {};
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = 0;
        }
        if (!("has_state" in $$source)) {
            this["has_state"] = false;
        }
        if (!("has_error" in $$source)) {
            this["has_error"] = false;
        }
        if (!("unsupported" in $$source)) {
            this["unsupported"] = {};
        }
        if (!("writable" in $$source)) {
            this["writable"] = false;
        }
        if (!("write_blocked" in $$source)) {
            this["write_blocked"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MozaBaseSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): MozaBaseSnapshot {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField2_0($$parsedSource["settings"]);
        }
        if ("temps" in $$parsedSource) {
            $$parsedSource["temps"] = $$createField3_0($$parsedSource["temps"]);
        }
        if ("unsupported" in $$parsedSource) {
            $$parsedSource["unsupported"] = $$createField8_0($$parsedSource["unsupported"]);
        }
        return new MozaBaseSnapshot($$parsedSource as Partial<MozaBaseSnapshot>);
    }
}

/**
 * MozaStatus reports the MOZA wheel's live state to the dashboard (polled like
 * the overlay/recording status). Enabled is the config intent; Connected is
 * whether a driver is actually open. Model/Serial/RPMLEDs are populated from USB
 * detection when the connected port maps to a known device.
 */
export class MozaStatus {
    "enabled": boolean;
    "connected": boolean;
    "port": string;
    "model": string;
    "serial": string;
    "rpm_leds": number;

    /**
     * Wheel is the attached rim's model code (e.g. "ES", "KS"), read over serial;
     * empty when no rim answered. Protocol is the effective LED protocol in use
     * ("new" or "old") once connected.
     */
    "wheel": string;
    "protocol": string;

    /** Creates a new MozaStatus instance. */
    constructor($$source: Partial<MozaStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("rpm_leds" in $$source)) {
            this["rpm_leds"] = 0;
        }
        if (!("wheel" in $$source)) {
            this["wheel"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MozaStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MozaStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MozaStatus($$parsedSource as Partial<MozaStatus>);
    }
}

/**
 * OverlayStatus reports the overlay's desired (user toggle) and actual
 * (native window) state. Enabled without Running means the overlay is on but
 * waiting for the game to start sending telemetry.
 */
export class OverlayStatus {
    "enabled": boolean;
    "running": boolean;

    /** Creates a new OverlayStatus instance. */
    constructor($$source: Partial<OverlayStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverlayStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): OverlayStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverlayStatus($$parsedSource as Partial<OverlayStatus>);
    }
}

/**
 * ReplaySample is a single telemetry frame from a recording, offset from the
 * start of the recording in milliseconds. Source/Meta mirror the live
 * TelemetrySnapshot so the dashboard can tailor a replay/review per game.
 */
export class ReplaySample {
    "offset_ms": number;
    "telemetry": forza$0.Telemetry;
    "source": string;
    "meta": TelemetryMeta;

    /** Creates a new ReplaySample instance. */
    constructor($$source: Partial<ReplaySample> = {}) {
        if (!("offset_ms" in $$source)) {
            this["offset_ms"] = 0;
        }
        if (!("telemetry" in $$source)) {
            this["telemetry"] = (new forza$0.Telemetry());
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new TelemetryMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplaySample instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplaySample {
        const $$createField1_0 = $$createType5;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("telemetry" in $$parsedSource) {
            $$parsedSource["telemetry"] = $$createField1_0($$parsedSource["telemetry"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField3_0($$parsedSource["meta"]);
        }
        return new ReplaySample($$parsedSource as Partial<ReplaySample>);
    }
}

/**
 * TelemetryMeta carries descriptive session info that does not fit the binary
 * forza.Telemetry model (which has no string fields). It is populated per source
 * — currently LMU, which sends the car/track names the dashboard's Info tab
 * shows. Forza leaves it zero-valued.
 */
export class TelemetryMeta {
    /**
     * vehicle/car name
     */
    "car": string;

    /**
     * track name
     */
    "track": string;

    /**
     * elapsed session time (seconds)
     */
    "session_time": number;

    /**
     * cars in the session
     */
    "num_vehicles": number;

    /**
     * SteeringRangeDeg is the car's lock-to-lock steering rotation in degrees
     * (LMU reports it per car). 0 when the game doesn't provide it (Forza), in
     * which case the overlay falls back to the configured default.
     */
    "steering_range_deg": number;

    /** Creates a new TelemetryMeta instance. */
    constructor($$source: Partial<TelemetryMeta> = {}) {
        if (!("car" in $$source)) {
            this["car"] = "";
        }
        if (!("track" in $$source)) {
            this["track"] = "";
        }
        if (!("session_time" in $$source)) {
            this["session_time"] = 0;
        }
        if (!("num_vehicles" in $$source)) {
            this["num_vehicles"] = 0;
        }
        if (!("steering_range_deg" in $$source)) {
            this["steering_range_deg"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TelemetryMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): TelemetryMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TelemetryMeta($$parsedSource as Partial<TelemetryMeta>);
    }
}

/**
 * TelemetrySnapshot is the latest parsed telemetry frame plus metadata about
 * when it was received. It is returned to the frontend over the Wails bindings.
 */
export class TelemetrySnapshot {
    "telemetry": forza$0.Telemetry;
    "received_at": time$0.Time;
    "available": boolean;

    /**
     * Source identifies the game that produced the latest frame ("forza" or
     * "lmu"), so the dashboard can tailor which tabs/readouts it shows. Empty
     * until the first packet arrives.
     */
    "source": string;

    /**
     * Meta is descriptive session info (car/track names, etc.) that has no place
     * in the binary telemetry struct. Surfaced on the dashboard's Info tab.
     */
    "meta": TelemetryMeta;

    /** Creates a new TelemetrySnapshot instance. */
    constructor($$source: Partial<TelemetrySnapshot> = {}) {
        if (!("telemetry" in $$source)) {
            this["telemetry"] = (new forza$0.Telemetry());
        }
        if (!("received_at" in $$source)) {
            this["received_at"] = null;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new TelemetryMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TelemetrySnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): TelemetrySnapshot {
        const $$createField0_0 = $$createType5;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("telemetry" in $$parsedSource) {
            $$parsedSource["telemetry"] = $$createField0_0($$parsedSource["telemetry"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField4_0($$parsedSource["meta"]);
        }
        return new TelemetrySnapshot($$parsedSource as Partial<TelemetrySnapshot>);
    }
}

/**
 * VoiceTestResult reports how long the test phrase took to become audible.
 * FirstAudioMS is the latency figure; TotalMS also includes speaking the phrase.
 */
export class VoiceTestResult {
    "first_audio_ms": number;
    "total_ms": number;

    /** Creates a new VoiceTestResult instance. */
    constructor($$source: Partial<VoiceTestResult> = {}) {
        if (!("first_audio_ms" in $$source)) {
            this["first_audio_ms"] = 0;
        }
        if (!("total_ms" in $$source)) {
            this["total_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoiceTestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): VoiceTestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VoiceTestResult($$parsedSource as Partial<VoiceTestResult>);
    }
}

/**
 * Zoomable is the slice of the Wails window the scale bindings need. Declaring
 * it here rather than taking the concrete window keeps app/ testable without a
 * GUI, and documents that this is the only window capability the service uses.
 */
export type Zoomable = any;

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = forza$0.Telemetry.createFrom;
const $$createType6 = TelemetryMeta.createFrom;
