// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface of the application. Its exported methods
 * are exposed to the React frontend as generated TypeScript bindings, mirroring
 * the JSON API the web server used to provide. It also owns the UDP receiver
 * loop and the overlay lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "../recording/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyConfig(cfg: config$0.Config): $CancellablePromise<config$0.Config> {
    return $Call.ByID(4123060480, cfg).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetConfig(): $CancellablePromise<config$0.Config> {
    return $Call.ByID(400336676).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetOverlayStatus(): $CancellablePromise<$models.OverlayStatus> {
    return $Call.ByID(2207766068).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetRecordingStatus(): $CancellablePromise<recording$0.Status> {
    return $Call.ByID(3118608443).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetTelemetry(): $CancellablePromise<$models.TelemetrySnapshot> {
    return $Call.ByID(3996014961).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListRecordings(): $CancellablePromise<recording$0.Info[]> {
    return $Call.ByID(632406974).then(($result: any) => {
        return $$createType5($result);
    });
}

export function PreviewMoza(moza: config$0.Moza): $CancellablePromise<void> {
    return $Call.ByID(3815721487, moza);
}

export function ReplayRecording(name: string, maxSamples: number): $CancellablePromise<$models.ReplaySample[]> {
    return $Call.ByID(1464642608, name, maxSamples).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SaveConfig(cfg: config$0.Config): $CancellablePromise<void> {
    return $Call.ByID(2475541833, cfg);
}

/**
 * SetOverlayEnabled toggles the native telemetry overlay on or off at runtime.
 */
export function SetOverlayEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1172459, enabled);
}

export function StartRecording(): $CancellablePromise<recording$0.Status> {
    return $Call.ByID(982748349).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StopRecording(): $CancellablePromise<recording$0.Status> {
    return $Call.ByID(1374983877).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $models.OverlayStatus.createFrom;
const $$createType2 = recording$0.Status.createFrom;
const $$createType3 = $models.TelemetrySnapshot.createFrom;
const $$createType4 = recording$0.Info.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.ReplaySample.createFrom;
const $$createType7 = $Create.Array($$createType6);
