// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface of the application. Its exported methods
 * are exposed to the React frontend as generated TypeScript bindings, mirroring
 * the JSON API the web server used to provide. It also owns the UDP receiver
 * loop and the overlay lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as analysis$0 from "../analysis/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../lmu/wire/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "../recording/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeRecording replays a saved recording and returns coaching analysis: a
 * per-lap scorecard plus a list of detected events. Pass maxSamples 0 to analyze
 * the whole recording.
 */
export function AnalyzeRecording(name: string, maxSamples: number): $CancellablePromise<analysis$0.Report> {
    return $Call.ByID(1855007469, name, maxSamples).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ApplyConfig(cfg: config$0.Config): $CancellablePromise<config$0.Config> {
    return $Call.ByID(4123060480, cfg).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetConfig(): $CancellablePromise<config$0.Config> {
    return $Call.ByID(400336676).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetConfigStatus(): $CancellablePromise<$models.ConfigStatus> {
    return $Call.ByID(4163477518).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLatestFrame returns the most recent full LMU telemetry frame — every car's
 * complete telemetry (engine, wheels/tires, suspension, forces, aero, damage,
 * electric boost) plus session globals (weather, rules, driving aids). It is
 * nil when the active source is Forza or no LMU frame has arrived yet.
 */
export function GetLatestFrame(): $CancellablePromise<wire$0.Frame | null> {
    return $Call.ByID(4261655122).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetMonitorInfo reports the logical resolution of the monitor the overlay will
 * appear on, used by the dashboard placement preview.
 */
export function GetMonitorInfo(): $CancellablePromise<$models.MonitorInfo> {
    return $Call.ByID(239629648).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetOverlayStatus(): $CancellablePromise<$models.OverlayStatus> {
    return $Call.ByID(2207766068).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetRecordingStatus(): $CancellablePromise<recording$0.Status> {
    return $Call.ByID(3118608443).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetTelemetry(): $CancellablePromise<$models.TelemetrySnapshot> {
    return $Call.ByID(3996014961).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListMonitors returns the names of all connected monitors for the overlay
 * output dropdown (empty when enumeration is unavailable, e.g. non-Hyprland).
 */
export function ListMonitors(): $CancellablePromise<string[]> {
    return $Call.ByID(4014067021).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListRecordings(): $CancellablePromise<recording$0.Info[]> {
    return $Call.ByID(632406974).then(($result: any) => {
        return $$createType11($result);
    });
}

export function PreviewMoza(moza: config$0.Moza): $CancellablePromise<void> {
    return $Call.ByID(3815721487, moza);
}

export function ReplayRecording(name: string, maxSamples: number): $CancellablePromise<$models.ReplaySample[]> {
    return $Call.ByID(1464642608, name, maxSamples).then(($result: any) => {
        return $$createType13($result);
    });
}

export function SaveConfig(cfg: config$0.Config): $CancellablePromise<void> {
    return $Call.ByID(2475541833, cfg);
}

/**
 * SetOverlayEnabled toggles the user's intent to show the native telemetry
 * overlay. The window itself only appears while the game is sending telemetry;
 * enabling it before the game starts simply arms it to show automatically.
 */
export function SetOverlayEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1172459, enabled);
}

export function StartRecording(): $CancellablePromise<recording$0.Status> {
    return $Call.ByID(982748349).then(($result: any) => {
        return $$createType7($result);
    });
}

export function StopRecording(): $CancellablePromise<recording$0.Status> {
    return $Call.ByID(1374983877).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = analysis$0.Report.createFrom;
const $$createType1 = config$0.Config.createFrom;
const $$createType2 = $models.ConfigStatus.createFrom;
const $$createType3 = wire$0.Frame.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.MonitorInfo.createFrom;
const $$createType6 = $models.OverlayStatus.createFrom;
const $$createType7 = recording$0.Status.createFrom;
const $$createType8 = $models.TelemetrySnapshot.createFrom;
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = recording$0.Info.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.ReplaySample.createFrom;
const $$createType13 = $Create.Array($$createType12);
