// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface of the application. Its exported methods
 * are exposed to the React frontend as generated TypeScript bindings, mirroring
 * the JSON API the web server used to provide. It also owns the UDP receiver
 * loop and the overlay lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as analysis$0 from "../analysis/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engineer$0 from "../engineer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rest$0 from "../game/lmu/rest/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../game/lmu/wire/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "../recording/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as moza$0 from "../wheelbase/moza/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeRecording replays a saved recording and returns coaching analysis: a
 * per-lap scorecard plus a list of detected events. Pass maxSamples 0 to analyze
 * the whole recording.
 */
export function AnalyzeRecording(name: string, maxSamples: number): $CancellablePromise<analysis$0.Report> {
    return $Call.ByID(1855007469, name, maxSamples).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ApplyConfig(cfg: config$0.Config): $CancellablePromise<config$0.Config> {
    return $Call.ByID(4123060480, cfg).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DetectMoza lists the MOZA wheels currently attached over USB so the dashboard
 * can show what is connected and let the user pick the serial port. Empty when
 * none are attached (or on platforms without detection).
 */
export function DetectMoza(): $CancellablePromise<moza$0.Device[]> {
    return $Call.ByID(3753523288).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetConfig(): $CancellablePromise<config$0.Config> {
    return $Call.ByID(400336676).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetConfigStatus(): $CancellablePromise<$models.ConfigStatus> {
    return $Call.ByID(4163477518).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetEngineerState returns the Strategy Planner's game-agnostic session model:
 * every car's position, gaps, fuel, tires and lap times, plus the global flag and
 * weather state. Available is false until the first LMU frame arrives (and resets
 * when the source switches to Forza). This is the single method the strategy
 * frontend polls.
 */
export function GetEngineerState(): $CancellablePromise<engineer$0.SessionState> {
    return $Call.ByID(1967406312).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetLatestFrame returns the most recent full LMU telemetry frame — every car's
 * complete telemetry (engine, wheels/tires, suspension, forces, aero, damage,
 * electric boost) plus session globals (weather, rules, driving aids). It is
 * nil when the active source is Forza or no LMU frame has arrived yet.
 */
export function GetLatestFrame(): $CancellablePromise<wire$0.Frame | null> {
    return $Call.ByID(4261655122).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetMonitorInfo reports the logical resolution of the monitor the overlay will
 * appear on, used by the dashboard placement preview.
 */
export function GetMonitorInfo(): $CancellablePromise<$models.MonitorInfo> {
    return $Call.ByID(239629648).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetMozaStatus reports whether the MOZA wheel is connected and, when USB
 * detection identifies it, its model/serial/rev-light count. Polled by the
 * dashboard's MOZA section to show live wheel info.
 */
export function GetMozaStatus(): $CancellablePromise<$models.MozaStatus> {
    return $Call.ByID(4221892961).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetOverlayStatus(): $CancellablePromise<$models.OverlayStatus> {
    return $Call.ByID(2207766068).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetRecordingStatus(): $CancellablePromise<recording$0.Status> {
    return $Call.ByID(3118608443).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetStrategyData returns the latest raw poll of LMU's REST API: pit-stop time
 * estimate, per-driver fuel/energy projections, vehicle condition, weather
 * forecast, full standings and the in-game pit menu. It is nil until the API has
 * been polled in an active LMU session (the higher-value bits are also merged
 * into GetEngineerState().Strategy; this exposes the full detail). The frontend
 * polls it for the Strategy Planner's richer views.
 */
export function GetStrategyData(): $CancellablePromise<rest$0.Snapshot | null> {
    return $Call.ByID(2558008555).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetTelemetry(): $CancellablePromise<$models.TelemetrySnapshot> {
    return $Call.ByID(3996014961).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ListIndexedRecordings returns the recordings index with track/car/source
 * metadata (newest first), or an empty list when persistence is unavailable.
 */
export function ListIndexedRecordings(): $CancellablePromise<store$0.RecordingRow[]> {
    return $Call.ByID(189090443).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ListMonitors returns the names of all connected monitors for the overlay
 * output dropdown (empty when enumeration is unavailable, e.g. non-Hyprland).
 */
export function ListMonitors(): $CancellablePromise<string[]> {
    return $Call.ByID(4014067021).then(($result: any) => {
        return $$createType17($result);
    });
}

export function ListRecordings(): $CancellablePromise<recording$0.Info[]> {
    return $Call.ByID(632406974).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * ListSessions returns the persisted session/stint history (newest first), or an
 * empty list when persistence is unavailable. Bound for the Strategy History view.
 */
export function ListSessions(): $CancellablePromise<store$0.SessionRow[]> {
    return $Call.ByID(660293959).then(($result: any) => {
        return $$createType21($result);
    });
}

export function PreviewMoza(moza: config$0.Moza): $CancellablePromise<void> {
    return $Call.ByID(3815721487, moza);
}

export function ReplayRecording(name: string, maxSamples: number): $CancellablePromise<$models.ReplaySample[]> {
    return $Call.ByID(1464642608, name, maxSamples).then(($result: any) => {
        return $$createType23($result);
    });
}

export function SaveConfig(cfg: config$0.Config): $CancellablePromise<void> {
    return $Call.ByID(2475541833, cfg);
}

/**
 * SetComparisonCar tells the strategy engine which rival to buffer a driven line
 * for (the Driver Vs. "line" overlay). The frontend calls it when the user picks
 * a comparison car; -1 clears the selection.
 */
export function SetComparisonCar(id: number): $CancellablePromise<void> {
    return $Call.ByID(3382318191, id);
}

/**
 * SetOverlayEnabled toggles the user's intent to show the native telemetry
 * overlay. The window itself only appears while the game is sending telemetry;
 * enabling it before the game starts simply arms it to show automatically.
 */
export function SetOverlayEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1172459, enabled);
}

export function StartRecording(): $CancellablePromise<recording$0.Status> {
    return $Call.ByID(982748349).then(($result: any) => {
        return $$createType11($result);
    });
}

export function StopRecording(): $CancellablePromise<recording$0.Status> {
    return $Call.ByID(1374983877).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * TestMozaLights runs a short rev-light sweep on the connected wheel so the user
 * can confirm the LEDs work from the dashboard's MOZA section (the same effect
 * as the -moza-test CLI). Errors if no wheel is connected.
 */
export function TestMozaLights(): $CancellablePromise<void> {
    return $Call.ByID(573481066);
}

// Private type creation functions
const $$createType0 = analysis$0.Report.createFrom;
const $$createType1 = config$0.Config.createFrom;
const $$createType2 = moza$0.Device.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ConfigStatus.createFrom;
const $$createType5 = engineer$0.SessionState.createFrom;
const $$createType6 = wire$0.Frame.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.MonitorInfo.createFrom;
const $$createType9 = $models.MozaStatus.createFrom;
const $$createType10 = $models.OverlayStatus.createFrom;
const $$createType11 = recording$0.Status.createFrom;
const $$createType12 = rest$0.Snapshot.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.TelemetrySnapshot.createFrom;
const $$createType15 = store$0.RecordingRow.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $Create.Array($Create.Any);
const $$createType18 = recording$0.Info.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = store$0.SessionRow.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $models.ReplaySample.createFrom;
const $$createType23 = $Create.Array($$createType22);
